<?php

/**
 * QueryCmOrderResponse.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Binance Derivatives Trading Portfolio Margin REST API.
 *
 * OpenAPI Specification for the Binance Derivatives Trading Portfolio Margin REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Binance\Client\DerivativesTradingPortfolioMargin\Model;

use Binance\Common\Dtos\ModelInterface;
use Binance\Common\ObjectSerializer;

/**
 * QueryCmOrderResponse Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class QueryCmOrderResponse implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'queryCmOrderResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'avgPrice' => 'string',
        'clientOrderId' => 'string',
        'cumBase' => 'string',
        'executedQty' => 'string',
        'orderId' => 'int',
        'origQty' => 'string',
        'origType' => 'string',
        'price' => 'string',
        'reduceOnly' => 'bool',
        'side' => 'string',
        'status' => 'string',
        'symbol' => 'string',
        'pair' => 'string',
        'positionSide' => 'string',
        'time' => 'int',
        'timeInForce' => 'string',
        'type' => 'string',
        'updateTime' => 'int',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'avgPrice' => null,
        'clientOrderId' => null,
        'cumBase' => null,
        'executedQty' => null,
        'orderId' => 'int64',
        'origQty' => null,
        'origType' => null,
        'price' => null,
        'reduceOnly' => null,
        'side' => null,
        'status' => null,
        'symbol' => null,
        'pair' => null,
        'positionSide' => null,
        'time' => 'int64',
        'timeInForce' => null,
        'type' => null,
        'updateTime' => 'int64',
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'avgPrice' => false,
        'clientOrderId' => false,
        'cumBase' => false,
        'executedQty' => false,
        'orderId' => false,
        'origQty' => false,
        'origType' => false,
        'price' => false,
        'reduceOnly' => false,
        'side' => false,
        'status' => false,
        'symbol' => false,
        'pair' => false,
        'positionSide' => false,
        'time' => false,
        'timeInForce' => false,
        'type' => false,
        'updateTime' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'avgPrice' => 'avgPrice',
        'clientOrderId' => 'clientOrderId',
        'cumBase' => 'cumBase',
        'executedQty' => 'executedQty',
        'orderId' => 'orderId',
        'origQty' => 'origQty',
        'origType' => 'origType',
        'price' => 'price',
        'reduceOnly' => 'reduceOnly',
        'side' => 'side',
        'status' => 'status',
        'symbol' => 'symbol',
        'pair' => 'pair',
        'positionSide' => 'positionSide',
        'time' => 'time',
        'timeInForce' => 'timeInForce',
        'type' => 'type',
        'updateTime' => 'updateTime',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'avgPrice' => 'setAvgPrice',
        'clientOrderId' => 'setClientOrderId',
        'cumBase' => 'setCumBase',
        'executedQty' => 'setExecutedQty',
        'orderId' => 'setOrderId',
        'origQty' => 'setOrigQty',
        'origType' => 'setOrigType',
        'price' => 'setPrice',
        'reduceOnly' => 'setReduceOnly',
        'side' => 'setSide',
        'status' => 'setStatus',
        'symbol' => 'setSymbol',
        'pair' => 'setPair',
        'positionSide' => 'setPositionSide',
        'time' => 'setTime',
        'timeInForce' => 'setTimeInForce',
        'type' => 'setType',
        'updateTime' => 'setUpdateTime',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'avgPrice' => 'getAvgPrice',
        'clientOrderId' => 'getClientOrderId',
        'cumBase' => 'getCumBase',
        'executedQty' => 'getExecutedQty',
        'orderId' => 'getOrderId',
        'origQty' => 'getOrigQty',
        'origType' => 'getOrigType',
        'price' => 'getPrice',
        'reduceOnly' => 'getReduceOnly',
        'side' => 'getSide',
        'status' => 'getStatus',
        'symbol' => 'getSymbol',
        'pair' => 'getPair',
        'positionSide' => 'getPositionSide',
        'time' => 'getTime',
        'timeInForce' => 'getTimeInForce',
        'type' => 'getType',
        'updateTime' => 'getUpdateTime',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param null|mixed[] $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('avgPrice', $data ?? [], null);
        $this->setIfExists('clientOrderId', $data ?? [], null);
        $this->setIfExists('cumBase', $data ?? [], null);
        $this->setIfExists('executedQty', $data ?? [], null);
        $this->setIfExists('orderId', $data ?? [], null);
        $this->setIfExists('origQty', $data ?? [], null);
        $this->setIfExists('origType', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('reduceOnly', $data ?? [], null);
        $this->setIfExists('side', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('symbol', $data ?? [], null);
        $this->setIfExists('pair', $data ?? [], null);
        $this->setIfExists('positionSide', $data ?? [], null);
        $this->setIfExists('time', $data ?? [], null);
        $this->setIfExists('timeInForce', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('updateTime', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * If oneOf schema, get the possible response types.
     */
    public static function getComposedSchemas(): array
    {
        return [
        ];
    }

    /**
     * Return true if the model is an array.
     */
    public static function isArray(): bool
    {
        return false;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets avgPrice.
     *
     * @return null|string
     */
    public function getAvgPrice()
    {
        return $this->container['avgPrice'];
    }

    /**
     * Sets avgPrice.
     *
     * @param null|string $avgPrice avgPrice
     *
     * @return self
     */
    public function setAvgPrice($avgPrice)
    {
        if (is_null($avgPrice)) {
            throw new \InvalidArgumentException('non-nullable avgPrice cannot be null');
        }
        $this->container['avgPrice'] = $avgPrice;

        return $this;
    }

    /**
     * Gets clientOrderId.
     *
     * @return null|string
     */
    public function getClientOrderId()
    {
        return $this->container['clientOrderId'];
    }

    /**
     * Sets clientOrderId.
     *
     * @param null|string $clientOrderId clientOrderId
     *
     * @return self
     */
    public function setClientOrderId($clientOrderId)
    {
        if (is_null($clientOrderId)) {
            throw new \InvalidArgumentException('non-nullable clientOrderId cannot be null');
        }
        $this->container['clientOrderId'] = $clientOrderId;

        return $this;
    }

    /**
     * Gets cumBase.
     *
     * @return null|string
     */
    public function getCumBase()
    {
        return $this->container['cumBase'];
    }

    /**
     * Sets cumBase.
     *
     * @param null|string $cumBase cumBase
     *
     * @return self
     */
    public function setCumBase($cumBase)
    {
        if (is_null($cumBase)) {
            throw new \InvalidArgumentException('non-nullable cumBase cannot be null');
        }
        $this->container['cumBase'] = $cumBase;

        return $this;
    }

    /**
     * Gets executedQty.
     *
     * @return null|string
     */
    public function getExecutedQty()
    {
        return $this->container['executedQty'];
    }

    /**
     * Sets executedQty.
     *
     * @param null|string $executedQty executedQty
     *
     * @return self
     */
    public function setExecutedQty($executedQty)
    {
        if (is_null($executedQty)) {
            throw new \InvalidArgumentException('non-nullable executedQty cannot be null');
        }
        $this->container['executedQty'] = $executedQty;

        return $this;
    }

    /**
     * Gets orderId.
     *
     * @return null|int
     */
    public function getOrderId()
    {
        return $this->container['orderId'];
    }

    /**
     * Sets orderId.
     *
     * @param null|int $orderId orderId
     *
     * @return self
     */
    public function setOrderId($orderId)
    {
        if (is_null($orderId)) {
            throw new \InvalidArgumentException('non-nullable orderId cannot be null');
        }
        $this->container['orderId'] = $orderId;

        return $this;
    }

    /**
     * Gets origQty.
     *
     * @return null|string
     */
    public function getOrigQty()
    {
        return $this->container['origQty'];
    }

    /**
     * Sets origQty.
     *
     * @param null|string $origQty origQty
     *
     * @return self
     */
    public function setOrigQty($origQty)
    {
        if (is_null($origQty)) {
            throw new \InvalidArgumentException('non-nullable origQty cannot be null');
        }
        $this->container['origQty'] = $origQty;

        return $this;
    }

    /**
     * Gets origType.
     *
     * @return null|string
     */
    public function getOrigType()
    {
        return $this->container['origType'];
    }

    /**
     * Sets origType.
     *
     * @param null|string $origType origType
     *
     * @return self
     */
    public function setOrigType($origType)
    {
        if (is_null($origType)) {
            throw new \InvalidArgumentException('non-nullable origType cannot be null');
        }
        $this->container['origType'] = $origType;

        return $this;
    }

    /**
     * Gets price.
     *
     * @return null|string
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price.
     *
     * @param null|string $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets reduceOnly.
     *
     * @return null|bool
     */
    public function getReduceOnly()
    {
        return $this->container['reduceOnly'];
    }

    /**
     * Sets reduceOnly.
     *
     * @param null|bool $reduceOnly reduceOnly
     *
     * @return self
     */
    public function setReduceOnly($reduceOnly)
    {
        if (is_null($reduceOnly)) {
            throw new \InvalidArgumentException('non-nullable reduceOnly cannot be null');
        }
        $this->container['reduceOnly'] = $reduceOnly;

        return $this;
    }

    /**
     * Gets side.
     *
     * @return null|string
     */
    public function getSide()
    {
        return $this->container['side'];
    }

    /**
     * Sets side.
     *
     * @param null|string $side side
     *
     * @return self
     */
    public function setSide($side)
    {
        if (is_null($side)) {
            throw new \InvalidArgumentException('non-nullable side cannot be null');
        }
        $this->container['side'] = $side;

        return $this;
    }

    /**
     * Gets status.
     *
     * @return null|string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status.
     *
     * @param null|string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets symbol.
     *
     * @return null|string
     */
    public function getSymbol()
    {
        return $this->container['symbol'];
    }

    /**
     * Sets symbol.
     *
     * @param null|string $symbol symbol
     *
     * @return self
     */
    public function setSymbol($symbol)
    {
        if (is_null($symbol)) {
            throw new \InvalidArgumentException('non-nullable symbol cannot be null');
        }
        $this->container['symbol'] = $symbol;

        return $this;
    }

    /**
     * Gets pair.
     *
     * @return null|string
     */
    public function getPair()
    {
        return $this->container['pair'];
    }

    /**
     * Sets pair.
     *
     * @param null|string $pair pair
     *
     * @return self
     */
    public function setPair($pair)
    {
        if (is_null($pair)) {
            throw new \InvalidArgumentException('non-nullable pair cannot be null');
        }
        $this->container['pair'] = $pair;

        return $this;
    }

    /**
     * Gets positionSide.
     *
     * @return null|string
     */
    public function getPositionSide()
    {
        return $this->container['positionSide'];
    }

    /**
     * Sets positionSide.
     *
     * @param null|string $positionSide positionSide
     *
     * @return self
     */
    public function setPositionSide($positionSide)
    {
        if (is_null($positionSide)) {
            throw new \InvalidArgumentException('non-nullable positionSide cannot be null');
        }
        $this->container['positionSide'] = $positionSide;

        return $this;
    }

    /**
     * Gets time.
     *
     * @return null|int
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time.
     *
     * @param null|int $time time
     *
     * @return self
     */
    public function setTime($time)
    {
        if (is_null($time)) {
            throw new \InvalidArgumentException('non-nullable time cannot be null');
        }
        $this->container['time'] = $time;

        return $this;
    }

    /**
     * Gets timeInForce.
     *
     * @return null|string
     */
    public function getTimeInForce()
    {
        return $this->container['timeInForce'];
    }

    /**
     * Sets timeInForce.
     *
     * @param null|string $timeInForce timeInForce
     *
     * @return self
     */
    public function setTimeInForce($timeInForce)
    {
        if (is_null($timeInForce)) {
            throw new \InvalidArgumentException('non-nullable timeInForce cannot be null');
        }
        $this->container['timeInForce'] = $timeInForce;

        return $this;
    }

    /**
     * Gets type.
     *
     * @return null|string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type.
     *
     * @param null|string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets updateTime.
     *
     * @return null|int
     */
    public function getUpdateTime()
    {
        return $this->container['updateTime'];
    }

    /**
     * Sets updateTime.
     *
     * @param null|int $updateTime updateTime
     *
     * @return self
     */
    public function setUpdateTime($updateTime)
    {
        if (is_null($updateTime)) {
            throw new \InvalidArgumentException('non-nullable updateTime cannot be null');
        }
        $this->container['updateTime'] = $updateTime;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
