<?php

/**
 * BfusdApiTest
 * PHP version 8.1.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Binance Simple Earn REST API.
 *
 * OpenAPI Specification for the Binance Simple Earn REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Binance\Client\SimpleEarn\Test\Api;

use Binance\Client\SimpleEarn\Api\BfusdApi;
use Binance\Client\SimpleEarn\Model\RedeemBfusdRequest;
use Binance\Client\SimpleEarn\Model\SubscribeBfusdRequest;
use Binance\Common\Configuration\ClientConfiguration;
use Binance\Common\Configuration\SignatureConfiguration;
use Binance\Common\HttpClient;
use GuzzleHttp\Psr7\Utils;
use PHPUnit\Framework\TestCase;
use Psr\Http\Message\ResponseInterface;

/**
 * BfusdApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @internal
 *
 * @coversNothing
 */
class BfusdApiTest extends TestCase
{
    public function getApiMock(&$request)
    {
        $clientMock = $this->createMock(HttpClient::class);
        $signatureConfig = new SignatureConfiguration();
        $signatureConfig->setApiKey('apiKey');
        $signatureConfig->setSecretKey('secretKey');
        $clientConfig = new ClientConfiguration();
        $clientConfig->setUrl('http://localhost:8080');
        $clientConfig->setSignatureConfiguration($signatureConfig);
        $responseMock = $this->createMock(ResponseInterface::class);

        $responseMock->expects($this->any())
            ->method('getStatusCode')
            ->willReturn(200)
        ;

        $responseMock->expects($this->any())
            ->method('getBody')
            ->willReturn(Utils::streamFor('{}'))
        ;

        $clientMock->expects($this->once())
            ->method('send')
            ->will($this->returnCallback(function ($actualRequest) use (&$request, $responseMock) {
                $request = $actualRequest;

                return $responseMock;
            }))
        ;

        $apiMock = $this->getMockBuilder(BfusdApi::class)
            ->setConstructorArgs([$clientConfig, $clientMock])
            ->onlyMethods(['getTimestamp'])
            ->getMock()
        ;

        $apiMock->method('getTimestamp')->willReturn('1736393892000');

        return $apiMock;
    }

    /**
     * Test case for getBfusdAccount.
     *
     * Get BFUSD Account (USER_DATA).
     */
    public function testGetBfusdAccount()
    {
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getBfusdAccount($recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/bfusd/account', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for getBfusdQuotaDetails.
     *
     * Get BFUSD Quota Details (USER_DATA).
     */
    public function testGetBfusdQuotaDetails()
    {
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getBfusdQuotaDetails($recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/bfusd/quota', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for getBfusdRateHistory.
     *
     * Get BFUSD Rate History (USER_DATA).
     */
    public function testGetBfusdRateHistory()
    {
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $current = 1;
        $size = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getBfusdRateHistory($startTime, $endTime, $current, $size, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/bfusd/history/rateHistory', $request->getUri()->getPath());
        self::assertEquals('2ecc0415a3bdb2963e8030cdf6cf00de6f49d21b71ff939dda42e5756eb8ba66', $queryMap['signature']);
    }

    /**
     * Test case for getBfusdRedemptionHistory.
     *
     * Get BFUSD Redemption History (USER_DATA).
     */
    public function testGetBfusdRedemptionHistory()
    {
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $current = 1;
        $size = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getBfusdRedemptionHistory($startTime, $endTime, $current, $size, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/bfusd/history/redemptionHistory', $request->getUri()->getPath());
        self::assertEquals('2ecc0415a3bdb2963e8030cdf6cf00de6f49d21b71ff939dda42e5756eb8ba66', $queryMap['signature']);
    }

    /**
     * Test case for getBfusdRewardsHistory.
     *
     * Get BFUSD Rewards History (USER_DATA).
     */
    public function testGetBfusdRewardsHistory()
    {
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $current = 1;
        $size = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getBfusdRewardsHistory($startTime, $endTime, $current, $size, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/bfusd/history/rewardsHistory', $request->getUri()->getPath());
        self::assertEquals('2ecc0415a3bdb2963e8030cdf6cf00de6f49d21b71ff939dda42e5756eb8ba66', $queryMap['signature']);
    }

    /**
     * Test case for getBfusdSubscriptionHistory.
     *
     * Get BFUSD subscription history(USER_DATA).
     */
    public function testGetBfusdSubscriptionHistory()
    {
        $asset = '';
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $current = 1;
        $size = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getBfusdSubscriptionHistory($asset, $startTime, $endTime, $current, $size, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/bfusd/history/subscriptionHistory', $request->getUri()->getPath());
        self::assertEquals('2ecc0415a3bdb2963e8030cdf6cf00de6f49d21b71ff939dda42e5756eb8ba66', $queryMap['signature']);
    }

    /**
     * Test case for redeemBfusd.
     *
     * Redeem BFUSD(TRADE).
     */
    public function testRedeemBfusd()
    {
        $redeemBfusdRequest = new RedeemBfusdRequest();
        $redeemBfusdRequest->setAmount(1.0);
        $redeemBfusdRequest->setType('s');

        $response = $this->getApiMock($request)->redeemBfusd($redeemBfusdRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/bfusd/redeem', $request->getUri()->getPath());
        self::assertEquals('cf4d90f2277c1ba7333541d98a46b5a20660ee8f7f9646faf427f1fa49e1c82c', $queryMap['signature']);
    }

    /**
     * Test case for subscribeBfusd.
     *
     * Subscribe BFUSD(TRADE).
     */
    public function testSubscribeBfusd()
    {
        $subscribeBfusdRequest = new SubscribeBfusdRequest();
        $subscribeBfusdRequest->setAsset('');
        $subscribeBfusdRequest->setAmount(1.0);

        $response = $this->getApiMock($request)->subscribeBfusd($subscribeBfusdRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/bfusd/subscribe', $request->getUri()->getPath());
        self::assertEquals('50d24733794b928836575c346769be26ee1fb5ffbf73f36933cd22c50116f74e', $queryMap['signature']);
    }
}
