<?php

/**
 * TrailingDeltaFilter.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Binance Spot REST API.
 *
 * OpenAPI Specifications for the Binance Spot REST API  API documents:   - [Github rest-api documentation file](https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md)   - [General API information for rest-api on website](https://developers.binance.com/docs/binance-spot-api-docs/rest-api/general-api-information)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Binance\Client\Spot\Model;

use Binance\Common\Dtos\ModelInterface;
use Binance\Common\ObjectSerializer;

/**
 * TrailingDeltaFilter Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class TrailingDeltaFilter implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TrailingDeltaFilter';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'filterType' => 'string',
        'minTrailingAboveDelta' => 'int',
        'maxTrailingAboveDelta' => 'int',
        'minTrailingBelowDelta' => 'int',
        'maxTrailingBelowDelta' => 'int',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'filterType' => null,
        'minTrailingAboveDelta' => 'int64',
        'maxTrailingAboveDelta' => 'int64',
        'minTrailingBelowDelta' => 'int64',
        'maxTrailingBelowDelta' => 'int64',
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'filterType' => false,
        'minTrailingAboveDelta' => false,
        'maxTrailingAboveDelta' => false,
        'minTrailingBelowDelta' => false,
        'maxTrailingBelowDelta' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'filterType' => 'filterType',
        'minTrailingAboveDelta' => 'minTrailingAboveDelta',
        'maxTrailingAboveDelta' => 'maxTrailingAboveDelta',
        'minTrailingBelowDelta' => 'minTrailingBelowDelta',
        'maxTrailingBelowDelta' => 'maxTrailingBelowDelta',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'filterType' => 'setFilterType',
        'minTrailingAboveDelta' => 'setMinTrailingAboveDelta',
        'maxTrailingAboveDelta' => 'setMaxTrailingAboveDelta',
        'minTrailingBelowDelta' => 'setMinTrailingBelowDelta',
        'maxTrailingBelowDelta' => 'setMaxTrailingBelowDelta',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'filterType' => 'getFilterType',
        'minTrailingAboveDelta' => 'getMinTrailingAboveDelta',
        'maxTrailingAboveDelta' => 'getMaxTrailingAboveDelta',
        'minTrailingBelowDelta' => 'getMinTrailingBelowDelta',
        'maxTrailingBelowDelta' => 'getMaxTrailingBelowDelta',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param null|mixed[] $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('filterType', $data ?? [], null);
        $this->setIfExists('minTrailingAboveDelta', $data ?? [], null);
        $this->setIfExists('maxTrailingAboveDelta', $data ?? [], null);
        $this->setIfExists('minTrailingBelowDelta', $data ?? [], null);
        $this->setIfExists('maxTrailingBelowDelta', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * If oneOf schema, get the possible response types.
     */
    public static function getComposedSchemas(): array
    {
        return [
        ];
    }

    /**
     * Return true if the model is an array.
     */
    public static function isArray(): bool
    {
        return false;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets filterType.
     *
     * @return null|string
     */
    public function getFilterType()
    {
        return $this->container['filterType'];
    }

    /**
     * Sets filterType.
     *
     * @param null|string $filterType filterType
     *
     * @return self
     */
    public function setFilterType($filterType)
    {
        if (is_null($filterType)) {
            throw new \InvalidArgumentException('non-nullable filterType cannot be null');
        }
        $this->container['filterType'] = $filterType;

        return $this;
    }

    /**
     * Gets minTrailingAboveDelta.
     *
     * @return null|int
     */
    public function getMinTrailingAboveDelta()
    {
        return $this->container['minTrailingAboveDelta'];
    }

    /**
     * Sets minTrailingAboveDelta.
     *
     * @param null|int $minTrailingAboveDelta minTrailingAboveDelta
     *
     * @return self
     */
    public function setMinTrailingAboveDelta($minTrailingAboveDelta)
    {
        if (is_null($minTrailingAboveDelta)) {
            throw new \InvalidArgumentException('non-nullable minTrailingAboveDelta cannot be null');
        }
        $this->container['minTrailingAboveDelta'] = $minTrailingAboveDelta;

        return $this;
    }

    /**
     * Gets maxTrailingAboveDelta.
     *
     * @return null|int
     */
    public function getMaxTrailingAboveDelta()
    {
        return $this->container['maxTrailingAboveDelta'];
    }

    /**
     * Sets maxTrailingAboveDelta.
     *
     * @param null|int $maxTrailingAboveDelta maxTrailingAboveDelta
     *
     * @return self
     */
    public function setMaxTrailingAboveDelta($maxTrailingAboveDelta)
    {
        if (is_null($maxTrailingAboveDelta)) {
            throw new \InvalidArgumentException('non-nullable maxTrailingAboveDelta cannot be null');
        }
        $this->container['maxTrailingAboveDelta'] = $maxTrailingAboveDelta;

        return $this;
    }

    /**
     * Gets minTrailingBelowDelta.
     *
     * @return null|int
     */
    public function getMinTrailingBelowDelta()
    {
        return $this->container['minTrailingBelowDelta'];
    }

    /**
     * Sets minTrailingBelowDelta.
     *
     * @param null|int $minTrailingBelowDelta minTrailingBelowDelta
     *
     * @return self
     */
    public function setMinTrailingBelowDelta($minTrailingBelowDelta)
    {
        if (is_null($minTrailingBelowDelta)) {
            throw new \InvalidArgumentException('non-nullable minTrailingBelowDelta cannot be null');
        }
        $this->container['minTrailingBelowDelta'] = $minTrailingBelowDelta;

        return $this;
    }

    /**
     * Gets maxTrailingBelowDelta.
     *
     * @return null|int
     */
    public function getMaxTrailingBelowDelta()
    {
        return $this->container['maxTrailingBelowDelta'];
    }

    /**
     * Sets maxTrailingBelowDelta.
     *
     * @param null|int $maxTrailingBelowDelta maxTrailingBelowDelta
     *
     * @return self
     */
    public function setMaxTrailingBelowDelta($maxTrailingBelowDelta)
    {
        if (is_null($maxTrailingBelowDelta)) {
            throw new \InvalidArgumentException('non-nullable maxTrailingBelowDelta cannot be null');
        }
        $this->container['maxTrailingBelowDelta'] = $maxTrailingBelowDelta;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
