<?php

/**
 * ApiManagementApiTest
 * PHP version 8.1.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Sub Account REST API.
 *
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Binance\Client\SubAccount\Test\Api;

use Binance\Client\SubAccount\Api\ApiManagementApi;
use Binance\Client\SubAccount\Model\AddIpRestrictionForSubAccountApiKeyRequest;
use Binance\Client\SubAccount\Model\CreateSubAccountApiKeyRequest;
use Binance\Client\SubAccount\Model\ModifySubAccountApiKeyPermissionRequest;
use Binance\Common\Configuration\ClientConfiguration;
use Binance\Common\Configuration\SignatureConfiguration;
use Binance\Common\HttpClient;
use GuzzleHttp\Psr7\Utils;
use PHPUnit\Framework\TestCase;
use Psr\Http\Message\ResponseInterface;

/**
 * ApiManagementApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @internal
 *
 * @coversNothing
 */
class ApiManagementApiTest extends TestCase
{
    public function getApiMock(&$request)
    {
        $clientMock = $this->createMock(HttpClient::class);
        $signatureConfig = new SignatureConfiguration();
        $signatureConfig->setApiKey('apiKey');
        $signatureConfig->setSecretKey('secretKey');
        $clientConfig = new ClientConfiguration();
        $clientConfig->setUrl('http://localhost:8080');
        $clientConfig->setSignatureConfiguration($signatureConfig);
        $responseMock = $this->createMock(ResponseInterface::class);

        $responseMock->expects($this->any())
            ->method('getStatusCode')
            ->willReturn(200)
        ;

        $responseMock->expects($this->any())
            ->method('getBody')
            ->willReturn(Utils::streamFor('{}'))
        ;

        $clientMock->expects($this->once())
            ->method('send')
            ->will($this->returnCallback(function ($actualRequest) use (&$request, $responseMock) {
                $request = $actualRequest;

                return $responseMock;
            }))
        ;

        $apiMock = $this->getMockBuilder(ApiManagementApi::class)
            ->setConstructorArgs([$clientConfig, $clientMock])
            ->onlyMethods(['getTimestamp'])
            ->getMock()
        ;

        $apiMock->method('getTimestamp')->willReturn('1736393892000');

        return $apiMock;
    }

    /**
     * Test case for addIpRestrictionForSubAccountApiKey.
     *
     * Add IP Restriction for Sub-Account API key (For Master Account) (USER_DATA).
     */
    public function testAddIpRestrictionForSubAccountApiKey()
    {
        $addIpRestrictionForSubAccountApiKeyRequest = new AddIpRestrictionForSubAccountApiKeyRequest();
        $addIpRestrictionForSubAccountApiKeyRequest->setEmail('123@test.com');
        $addIpRestrictionForSubAccountApiKeyRequest->setSubAccountApiKey('k5V49ldtn4tszj6W3hystegdfvmGbqDzjmkCtpTvC0G74WhK7yd4rfCTo4lShf');
        $addIpRestrictionForSubAccountApiKeyRequest->setStatus(1);

        $response = $this->getApiMock($request)->addIpRestrictionForSubAccountApiKey($addIpRestrictionForSubAccountApiKeyRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v2/sub-account/subAccountApi/ipRestriction', $request->getUri()->getPath());
        self::assertEquals('4d948008a78beebb1737cd5da5f728b1d17bdad20a16310d545530a3d5a85090', $queryMap['signature']);
    }

    /**
     * Test case for createSubAccountApiKey.
     *
     * Create Sub-account API Key (For Master Account) (USER_DATA).
     */
    public function testCreateSubAccountApiKey()
    {
        $createSubAccountApiKeyRequest = new CreateSubAccountApiKeyRequest();
        $createSubAccountApiKeyRequest->setEmail('123@test.com');
        $createSubAccountApiKeyRequest->setApiName('myKey');
        $createSubAccountApiKeyRequest->setStatus(2);

        $response = $this->getApiMock($request)->createSubAccountApiKey($createSubAccountApiKeyRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/subAccountApi', $request->getUri()->getPath());
        self::assertEquals('e5835c353271ded250669639472a5accc957c9a8e3d8654a6c007bd83d45554a', $queryMap['signature']);
    }

    /**
     * Test case for deleteIpListForASubAccountApiKey.
     *
     * Delete IP List For a Sub-account API Key (For Master Account) (USER_DATA).
     */
    public function testDeleteIpListForASubAccountApiKey()
    {
        $email = '123@test.com';
        $subAccountApiKey = 'k5V49ldtn4tszj6W3hystegdfvmGbqDzjmkCtpTvC0G74WhK7yd4rfCTo4lShf';
        $ipAddress = '69.210.67.14';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->deleteIpListForASubAccountApiKey($email, $subAccountApiKey, $ipAddress, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/subAccountApi/ipRestriction/ipList', $request->getUri()->getPath());
        self::assertEquals('fcf6da2e048cde255b743acc675bf3d57be293cec543273c464be1bc04a24bef', $queryMap['signature']);
    }

    /**
     * Test case for deleteSubAccountApiKey.
     *
     * Delete Sub-account API Key (For Master Account) (USER_DATA).
     */
    public function testDeleteSubAccountApiKey()
    {
        $email = '123@test.com';
        $subAccountApiKey = 'k5V49ldtn4tszj6W3hystegdfvmGbqDzjmkCtpTvC0G74WhK7yd4rfCTo4lShf';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->deleteSubAccountApiKey($email, $subAccountApiKey, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/subAccountApi', $request->getUri()->getPath());
        self::assertEquals('80e6a8dde164d84d85ddb6a4aa6079b30842518b288430f6cf260f1c70069c30', $queryMap['signature']);
    }

    /**
     * Test case for getIpRestrictionForASubAccountApiKey.
     *
     * Get IP Restriction for a Sub-account API Key (For Master Account) (USER_DATA).
     */
    public function testGetIpRestrictionForASubAccountApiKey()
    {
        $email = '123@test.com';
        $subAccountApiKey = 'k5V49ldtn4tszj6W3hystegdfvmGbqDzjmkCtpTvC0G74WhK7yd4rfCTo4lShf';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getIpRestrictionForASubAccountApiKey($email, $subAccountApiKey, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/subAccountApi/ipRestriction', $request->getUri()->getPath());
        self::assertEquals('80e6a8dde164d84d85ddb6a4aa6079b30842518b288430f6cf260f1c70069c30', $queryMap['signature']);
    }

    /**
     * Test case for modifySubAccountApiKeyPermission.
     *
     * Modify Sub-account API Key Permission (For Master Account) (USER_DATA).
     */
    public function testModifySubAccountApiKeyPermission()
    {
        $modifySubAccountApiKeyPermissionRequest = new ModifySubAccountApiKeyPermissionRequest();
        $modifySubAccountApiKeyPermissionRequest->setEmail('123@test.com');
        $modifySubAccountApiKeyPermissionRequest->setSubAccountApiKey('k5V49ldtn4tszj6W3hystegdfvmGbqDzjmkCtpTvC0G74WhK7yd4rfCTo4lShf');

        $response = $this->getApiMock($request)->modifySubAccountApiKeyPermission($modifySubAccountApiKeyPermissionRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/subAccountApiPermission', $request->getUri()->getPath());
        self::assertEquals('3a357027fbf1267d2eac6c03f6b8b46ec53c7a495b5898e60075068cbf6ece49', $queryMap['signature']);
    }

    /**
     * Test case for querySubAccountApiKey.
     *
     * Query Sub-account API Key (For Master Account) (USER_DATA).
     */
    public function testQuerySubAccountApiKey()
    {
        $email = '123@test.com';
        $subAccountApiKey = 'k5V49ldtn4tszj6W3hystegdfvmGbqDzjmkCtpTvC0G74WhK7yd4rfCTo4lShf';
        $page = 1;
        $size = 30;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->querySubAccountApiKey($email, $subAccountApiKey, $page, $size, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/subAccountApi', $request->getUri()->getPath());
        self::assertEquals('352ad470dd82f59a301f0fd900b181fdab2fe9f33c3fd6cad968480b7aa41b28', $queryMap['signature']);
    }
}
