<?php

/**
 * AssetManagementApiTest
 * PHP version 8.1.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Sub Account REST API.
 *
 * Create and manage sub-accounts, control permissions, and transfer assets via the Sub Account API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Binance\Client\SubAccount\Test\Api;

use Binance\Client\SubAccount\Api\AssetManagementApi;
use Binance\Client\SubAccount\Model\FromAccountType;
use Binance\Client\SubAccount\Model\FuturesTransferForSubAccountRequest;
use Binance\Client\SubAccount\Model\MarginTransferForSubAccountRequest;
use Binance\Client\SubAccount\Model\MovePositionForSubAccountRequest;
use Binance\Client\SubAccount\Model\OrderArgs;
use Binance\Client\SubAccount\Model\ProductType;
use Binance\Client\SubAccount\Model\SubAccountFuturesAssetTransferRequest;
use Binance\Client\SubAccount\Model\ToAccountType;
use Binance\Client\SubAccount\Model\TransferToMasterRequest;
use Binance\Client\SubAccount\Model\TransferToSubAccountOfSameMasterRequest;
use Binance\Client\SubAccount\Model\UniversalTransferRequest;
use Binance\Common\Configuration\ClientConfiguration;
use Binance\Common\Configuration\SignatureConfiguration;
use Binance\Common\HttpClient;
use GuzzleHttp\Psr7\Utils;
use PHPUnit\Framework\TestCase;
use Psr\Http\Message\ResponseInterface;

/**
 * AssetManagementApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @internal
 *
 * @coversNothing
 */
class AssetManagementApiTest extends TestCase
{
    public function getApiMock(&$request)
    {
        $clientMock = $this->createMock(HttpClient::class);
        $signatureConfig = new SignatureConfiguration();
        $signatureConfig->setApiKey('apiKey');
        $signatureConfig->setSecretKey('secretKey');
        $clientConfig = new ClientConfiguration();
        $clientConfig->setUrl('http://localhost:8080');
        $clientConfig->setSignatureConfiguration($signatureConfig);
        $responseMock = $this->createMock(ResponseInterface::class);

        $responseMock->expects($this->any())
            ->method('getStatusCode')
            ->willReturn(200)
        ;

        $responseMock->expects($this->any())
            ->method('getBody')
            ->willReturn(Utils::streamFor('{}'))
        ;

        $clientMock->expects($this->once())
            ->method('send')
            ->will($this->returnCallback(function ($actualRequest) use (&$request, $responseMock) {
                $request = $actualRequest;

                return $responseMock;
            }))
        ;

        $apiMock = $this->getMockBuilder(AssetManagementApi::class)
            ->setConstructorArgs([$clientConfig, $clientMock])
            ->onlyMethods(['getTimestamp'])
            ->getMock()
        ;

        $apiMock->method('getTimestamp')->willReturn('1736393892000');

        return $apiMock;
    }

    /**
     * Test case for futuresTransferForSubAccount.
     *
     * Futures Transfer for Sub-account (For Master Account) (USER_DATA).
     */
    public function testFuturesTransferForSubAccount()
    {
        $futuresTransferForSubAccountRequest = new FuturesTransferForSubAccountRequest();
        $futuresTransferForSubAccountRequest->setEmail('123@test.com');
        $futuresTransferForSubAccountRequest->setAsset('USDT');
        $futuresTransferForSubAccountRequest->setAmount(1.0);
        $futuresTransferForSubAccountRequest->setType(1);

        $response = $this->getApiMock($request)->futuresTransferForSubAccount($futuresTransferForSubAccountRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/futures/transfer', $request->getUri()->getPath());
        self::assertEquals('7d53e9abcefc3c5bf79790237e665e96c0f3c19332f802023e3c4e683a6b4b55', $queryMap['signature']);
    }

    /**
     * Test case for getDetailOnSubAccountsFuturesAccount.
     *
     * Get Detail on Sub-account's Futures Account (For Master Account) (USER_DATA).
     */
    public function testGetDetailOnSubAccountsFuturesAccount()
    {
        $email = '123@test.com';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getDetailOnSubAccountsFuturesAccount($email, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/futures/account', $request->getUri()->getPath());
        self::assertEquals('cd63404bc561d336289e8cb941b7cdf71a2a31b8167ead6c6b6d60e0279653ce', $queryMap['signature']);
    }

    /**
     * Test case for getDetailOnSubAccountsFuturesAccountV2.
     *
     * Get Detail on Sub-account's Futures Account V2 (For Master Account) (USER_DATA).
     */
    public function testGetDetailOnSubAccountsFuturesAccountV2()
    {
        $email = '123@test.com';
        $futuresType = 1;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getDetailOnSubAccountsFuturesAccountV2($email, $futuresType, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v2/sub-account/futures/account', $request->getUri()->getPath());
        self::assertEquals('26bcd5b994bb829b3a59484013a4fce2a60ba12d6f08fbe5a00173000cbe40c7', $queryMap['signature']);
    }

    /**
     * Test case for getDetailOnSubAccountsMarginAccount.
     *
     * Get Detail on Sub-account's Margin Account (For Master Account) (USER_DATA).
     */
    public function testGetDetailOnSubAccountsMarginAccount()
    {
        $email = '123@test.com';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getDetailOnSubAccountsMarginAccount($email, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/margin/account', $request->getUri()->getPath());
        self::assertEquals('cd63404bc561d336289e8cb941b7cdf71a2a31b8167ead6c6b6d60e0279653ce', $queryMap['signature']);
    }

    /**
     * Test case for getMovePositionHistoryForSubAccount.
     *
     * Get Move Position History for Sub-account (For Master Account) (USER_DATA).
     */
    public function testGetMovePositionHistoryForSubAccount()
    {
        $symbol = 'BTCUSDT';
        $page = 1;
        $rows = 1;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getMovePositionHistoryForSubAccount($symbol, $page, $rows, $startTime, $endTime, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/futures/move-position', $request->getUri()->getPath());
        self::assertEquals('8de4d8f77b968580be9fba1f25671a319d2930766c4b3aed8a43314b76a99423', $queryMap['signature']);
    }

    /**
     * Test case for getSubAccountDepositAddress.
     *
     * Get Sub-account Deposit Address (For Master Account) (USER_DATA).
     */
    public function testGetSubAccountDepositAddress()
    {
        $email = '123@test.com';
        $coin = 'BTC';
        $network = '';
        $amount = 1.0;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getSubAccountDepositAddress($email, $coin, $network, $amount, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/capital/deposit/subAddress', $request->getUri()->getPath());
        self::assertEquals('5f5bd3dbce9d10b96a67fe584289fb76c957d7d3f5794aac44b555d25f9c0fd5', $queryMap['signature']);
    }

    /**
     * Test case for getSubAccountDepositHistory.
     *
     * Get Sub-account Deposit History (For Master Account) (USER_DATA).
     */
    public function testGetSubAccountDepositHistory()
    {
        $email = '123@test.com';
        $includeSource = false;
        $coin = 'BTC';
        $status = 0;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $limit = 1;
        $offset = 0;
        $recvWindow = 5000;
        $txId = '1';
        $response = $this->getApiMock($request)->getSubAccountDepositHistory($email, $includeSource, $coin, $status, $startTime, $endTime, $limit, $offset, $recvWindow, $txId);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/capital/deposit/subHisrec', $request->getUri()->getPath());
        self::assertEquals('ad9815d7e54142a951eb3d10e1c96bed6c3aa4e60d63277865b587e5b7d75e83', $queryMap['signature']);
    }

    /**
     * Test case for getSummaryOfSubAccountsFuturesAccount.
     *
     * Get Summary of Sub-account's Futures Account (For Master Account) (USER_DATA).
     */
    public function testGetSummaryOfSubAccountsFuturesAccount()
    {
        $page = 1;
        $limit = 1;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getSummaryOfSubAccountsFuturesAccount($page, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/futures/accountSummary', $request->getUri()->getPath());
        self::assertEquals('8a73086a1b7b0b8fdd097b5e9651c03b0a8938014f4aae424ed1db47d1030ab6', $queryMap['signature']);
    }

    /**
     * Test case for getSummaryOfSubAccountsFuturesAccountV2.
     *
     * Get Summary of Sub-account's Futures Account V2 (For Master Account) (USER_DATA).
     */
    public function testGetSummaryOfSubAccountsFuturesAccountV2()
    {
        $futuresType = 1;
        $page = 1;
        $limit = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getSummaryOfSubAccountsFuturesAccountV2($futuresType, $page, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v2/sub-account/futures/accountSummary', $request->getUri()->getPath());
        self::assertEquals('92de66901bb7041e94ca3c2b3d89a9d1294d342396506a2a9a89d6958f336b2d', $queryMap['signature']);
    }

    /**
     * Test case for getSummaryOfSubAccountsMarginAccount.
     *
     * Get Summary of Sub-account's Margin Account (For Master Account) (USER_DATA).
     */
    public function testGetSummaryOfSubAccountsMarginAccount()
    {
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getSummaryOfSubAccountsMarginAccount($recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/margin/accountSummary', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for marginTransferForSubAccount.
     *
     * Margin Transfer for Sub-account (For Master Account) (USER_DATA).
     */
    public function testMarginTransferForSubAccount()
    {
        $marginTransferForSubAccountRequest = new MarginTransferForSubAccountRequest();
        $marginTransferForSubAccountRequest->setEmail('123@test.com');
        $marginTransferForSubAccountRequest->setAsset('BTC');
        $marginTransferForSubAccountRequest->setAmount(1.0);
        $marginTransferForSubAccountRequest->setType(1);

        $response = $this->getApiMock($request)->marginTransferForSubAccount($marginTransferForSubAccountRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/margin/transfer', $request->getUri()->getPath());
        self::assertEquals('3e600a3f71046d5e56cb74b30d80468d93a079da00c5f6ac8e916401175ed186', $queryMap['signature']);
    }

    /**
     * Test case for movePositionForSubAccount.
     *
     * Move Position for Sub-account (For Master Account) (USER_DATA).
     */
    public function testMovePositionForSubAccount()
    {
        $movePositionForSubAccountRequest = new MovePositionForSubAccountRequest();
        $movePositionForSubAccountRequest->setFromUserEmail('testFrom@google.com');
        $movePositionForSubAccountRequest->setToUserEmail('testTo@google.com');
        $movePositionForSubAccountRequest->setProductType(ProductType::UM);
        $movePositionForSubAccountRequest->setOrderArgs(new OrderArgs());

        $response = $this->getApiMock($request)->movePositionForSubAccount($movePositionForSubAccountRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/futures/move-position', $request->getUri()->getPath());
        self::assertEquals('8803c3573413137c73516d70abc8242d3d87846394da2875d95ce6c3a9be8ebb', $queryMap['signature']);
    }

    /**
     * Test case for querySubAccountAssets.
     *
     * Query Sub-account Assets (For Master Account) (USER_DATA).
     */
    public function testQuerySubAccountAssets()
    {
        $email = '123@test.com';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->querySubAccountAssets($email, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v3/sub-account/assets', $request->getUri()->getPath());
        self::assertEquals('cd63404bc561d336289e8cb941b7cdf71a2a31b8167ead6c6b6d60e0279653ce', $queryMap['signature']);
    }

    /**
     * Test case for querySubAccountAssetsAssetManagement.
     *
     * Query Sub-account Assets V4 (For Master Account) (USER_DATA).
     */
    public function testQuerySubAccountAssetsAssetManagement()
    {
        $email = '123@test.com';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->querySubAccountAssetsAssetManagement($email, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v4/sub-account/assets', $request->getUri()->getPath());
        self::assertEquals('cd63404bc561d336289e8cb941b7cdf71a2a31b8167ead6c6b6d60e0279653ce', $queryMap['signature']);
    }

    /**
     * Test case for querySubAccountFuturesAssetTransferHistory.
     *
     * Query Sub-account Futures Asset Transfer History (For Master Account) (USER_DATA).
     */
    public function testQuerySubAccountFuturesAssetTransferHistory()
    {
        $email = '123@test.com';
        $futuresType = 1;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $page = 1;
        $limit = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->querySubAccountFuturesAssetTransferHistory($email, $futuresType, $startTime, $endTime, $page, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/futures/internalTransfer', $request->getUri()->getPath());
        self::assertEquals('fd0fcd6f5728a7271cffd9fca3460d0702847009aae87971969ac28f728697b7', $queryMap['signature']);
    }

    /**
     * Test case for querySubAccountSpotAssetTransferHistory.
     *
     * Query Sub-account Spot Asset Transfer History (For Master Account) (USER_DATA).
     */
    public function testQuerySubAccountSpotAssetTransferHistory()
    {
        $fromEmail = 'aaa@test.com';
        $toEmail = 'bbb@test.com';
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $page = 1;
        $limit = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->querySubAccountSpotAssetTransferHistory($fromEmail, $toEmail, $startTime, $endTime, $page, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/sub/transfer/history', $request->getUri()->getPath());
        self::assertEquals('380f287e79c1bf8fc0d5d115153310b032b2fbba418a461b6969c0461cb564d6', $queryMap['signature']);
    }

    /**
     * Test case for querySubAccountSpotAssetsSummary.
     *
     * Query Sub-account Spot Assets Summary (For Master Account) (USER_DATA).
     */
    public function testQuerySubAccountSpotAssetsSummary()
    {
        $email = '123@test.com';
        $page = 1;
        $size = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->querySubAccountSpotAssetsSummary($email, $page, $size, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/spotSummary', $request->getUri()->getPath());
        self::assertEquals('9029a18d45f4a77c0c74df77bdb6839600bd23be68520dca80fe9697ef906e63', $queryMap['signature']);
    }

    /**
     * Test case for queryUniversalTransferHistory.
     *
     * Query Universal Transfer History (For Master Account) (USER_DATA).
     */
    public function testQueryUniversalTransferHistory()
    {
        $fromEmail = 'abctest@gmail.com';
        $toEmail = 'deftest@gmail.com';
        $clientTranId = '1';
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $page = 1;
        $limit = 10;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->queryUniversalTransferHistory($fromEmail, $toEmail, $clientTranId, $startTime, $endTime, $page, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/universalTransfer', $request->getUri()->getPath());
        self::assertEquals('1cd85eef2d15a61441518a575c60a87e65f4f9ea3724d0b7ef7b1889b8a05a39', $queryMap['signature']);
    }

    /**
     * Test case for subAccountFuturesAssetTransfer.
     *
     * Sub-account Futures Asset Transfer (For Master Account) (USER_DATA).
     */
    public function testSubAccountFuturesAssetTransfer()
    {
        $subAccountFuturesAssetTransferRequest = new SubAccountFuturesAssetTransferRequest();
        $subAccountFuturesAssetTransferRequest->setFromEmail('abc@test.com');
        $subAccountFuturesAssetTransferRequest->setToEmail('def@test.com');
        $subAccountFuturesAssetTransferRequest->setFuturesType(1);
        $subAccountFuturesAssetTransferRequest->setAsset('BTC');
        $subAccountFuturesAssetTransferRequest->setAmount(1.0);

        $response = $this->getApiMock($request)->subAccountFuturesAssetTransfer($subAccountFuturesAssetTransferRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/futures/internalTransfer', $request->getUri()->getPath());
        self::assertEquals('1bf18cd4eb54c38204de9b3c54b24d4c9b6391dbc73fb71b2328cd6cca406d3a', $queryMap['signature']);
    }

    /**
     * Test case for subAccountTransferHistory.
     *
     * Sub-account Transfer History (For Sub-account) (USER_DATA).
     */
    public function testSubAccountTransferHistory()
    {
        $asset = 'BTC';
        $type = 1;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $limit = 10;
        $returnFailHistory = false;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->subAccountTransferHistory($asset, $type, $startTime, $endTime, $limit, $returnFailHistory, $recvWindow);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/transfer/subUserHistory', $request->getUri()->getPath());
        self::assertEquals('969bb015eeb3d1ae1acd05e28a092c9d5f1d1174a93d590ac884595fbd0b2c5f', $queryMap['signature']);
    }

    /**
     * Test case for transferToMaster.
     *
     * Transfer to Master (For Sub-account) (USER_DATA).
     */
    public function testTransferToMaster()
    {
        $transferToMasterRequest = new TransferToMasterRequest();
        $transferToMasterRequest->setAsset('BTC');
        $transferToMasterRequest->setAmount(1.0);

        $response = $this->getApiMock($request)->transferToMaster($transferToMasterRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/transfer/subToMaster', $request->getUri()->getPath());
        self::assertEquals('b071bb351f4c802bd2ea5e03650f81f218a9e1183eefc8fd1d5c10386df32529', $queryMap['signature']);
    }

    /**
     * Test case for transferToSubAccountOfSameMaster.
     *
     * Transfer to Sub-account of Same Master (For Sub-account) (USER_DATA).
     */
    public function testTransferToSubAccountOfSameMaster()
    {
        $transferToSubAccountOfSameMasterRequest = new TransferToSubAccountOfSameMasterRequest();
        $transferToSubAccountOfSameMasterRequest->setToEmail('abc@test.com');
        $transferToSubAccountOfSameMasterRequest->setAsset('BTC');
        $transferToSubAccountOfSameMasterRequest->setAmount(1.0);

        $response = $this->getApiMock($request)->transferToSubAccountOfSameMaster($transferToSubAccountOfSameMasterRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/transfer/subToSub', $request->getUri()->getPath());
        self::assertEquals('2db6521f82c1d77bee06e73c8eae9991cfefcb5129ed513bf788c55bf378fb22', $queryMap['signature']);
    }

    /**
     * Test case for universalTransfer.
     *
     * Universal Transfer (For Master Account) (USER_DATA).
     */
    public function testUniversalTransfer()
    {
        $universalTransferRequest = new UniversalTransferRequest();
        $universalTransferRequest->setFromAccountType(FromAccountType::SPOT);
        $universalTransferRequest->setToAccountType(ToAccountType::SPOT);
        $universalTransferRequest->setAsset('BTC');
        $universalTransferRequest->setAmount(1.0);

        $response = $this->getApiMock($request)->universalTransfer($universalTransferRequest);

        parse_str($request->getUri(), $queryMap);


        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/sub-account/universalTransfer', $request->getUri()->getPath());
        self::assertEquals('e3e0ccbff8bee94a92a5f270ab3455dae99c38cafd6d7e2ee0eaab991c721cdf', $queryMap['signature']);
    }
}
