<?php

/**
 * SourceAccount.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Staking REST API.
 *
 * Subscribe to staking products, track positions, and query rewards via the Binance Staking API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Binance\Client\Staking\Model;

/**
 * SourceAccount Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
enum SourceAccount: string
{
    /**
     * Possible values of this enum.
     */
    case SPOT = 'SPOT';

    case FUND = 'FUND';

    case ALL = 'ALL';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SPOT,
            self::FUND,
            self::ALL,
        ];
    }
}
