<?php

/**
 * MarginAccountNewOcoRequest.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Binance Margin Trading REST API.
 *
 * OpenAPI Specification for the Binance Margin Trading REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Binance\Client\MarginTrading\Model;

use Binance\Common\Dtos\ModelInterface;
use Binance\Common\ObjectSerializer;

/**
 * MarginAccountNewOcoRequest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class MarginAccountNewOcoRequest implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'marginAccountNewOcoRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'symbol' => 'string',
        'isIsolated' => 'string',
        'listClientOrderId' => 'string',
        'side' => '\Binance\Client\MarginTrading\Model\Side',
        'quantity' => 'float',
        'limitClientOrderId' => 'string',
        'price' => 'float',
        'limitIcebergQty' => 'float',
        'stopClientOrderId' => 'string',
        'stopPrice' => 'float',
        'stopLimitPrice' => 'float',
        'stopIcebergQty' => 'float',
        'stopLimitTimeInForce' => 'string',
        'newOrderRespType' => '\Binance\Client\MarginTrading\Model\NewOrderRespType',
        'sideEffectType' => 'string',
        'selfTradePreventionMode' => 'string',
        'autoRepayAtCancel' => 'bool',
        'recvWindow' => 'int',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'symbol' => null,
        'isIsolated' => null,
        'listClientOrderId' => null,
        'side' => null,
        'quantity' => 'float',
        'limitClientOrderId' => null,
        'price' => 'float',
        'limitIcebergQty' => 'float',
        'stopClientOrderId' => null,
        'stopPrice' => 'float',
        'stopLimitPrice' => 'float',
        'stopIcebergQty' => 'float',
        'stopLimitTimeInForce' => null,
        'newOrderRespType' => null,
        'sideEffectType' => null,
        'selfTradePreventionMode' => null,
        'autoRepayAtCancel' => null,
        'recvWindow' => 'int64',
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'symbol' => false,
        'isIsolated' => false,
        'listClientOrderId' => false,
        'side' => false,
        'quantity' => false,
        'limitClientOrderId' => false,
        'price' => false,
        'limitIcebergQty' => false,
        'stopClientOrderId' => false,
        'stopPrice' => false,
        'stopLimitPrice' => false,
        'stopIcebergQty' => false,
        'stopLimitTimeInForce' => false,
        'newOrderRespType' => false,
        'sideEffectType' => false,
        'selfTradePreventionMode' => false,
        'autoRepayAtCancel' => false,
        'recvWindow' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'symbol' => 'symbol',
        'isIsolated' => 'isIsolated',
        'listClientOrderId' => 'listClientOrderId',
        'side' => 'side',
        'quantity' => 'quantity',
        'limitClientOrderId' => 'limitClientOrderId',
        'price' => 'price',
        'limitIcebergQty' => 'limitIcebergQty',
        'stopClientOrderId' => 'stopClientOrderId',
        'stopPrice' => 'stopPrice',
        'stopLimitPrice' => 'stopLimitPrice',
        'stopIcebergQty' => 'stopIcebergQty',
        'stopLimitTimeInForce' => 'stopLimitTimeInForce',
        'newOrderRespType' => 'newOrderRespType',
        'sideEffectType' => 'sideEffectType',
        'selfTradePreventionMode' => 'selfTradePreventionMode',
        'autoRepayAtCancel' => 'autoRepayAtCancel',
        'recvWindow' => 'recvWindow',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'symbol' => 'setSymbol',
        'isIsolated' => 'setIsIsolated',
        'listClientOrderId' => 'setListClientOrderId',
        'side' => 'setSide',
        'quantity' => 'setQuantity',
        'limitClientOrderId' => 'setLimitClientOrderId',
        'price' => 'setPrice',
        'limitIcebergQty' => 'setLimitIcebergQty',
        'stopClientOrderId' => 'setStopClientOrderId',
        'stopPrice' => 'setStopPrice',
        'stopLimitPrice' => 'setStopLimitPrice',
        'stopIcebergQty' => 'setStopIcebergQty',
        'stopLimitTimeInForce' => 'setStopLimitTimeInForce',
        'newOrderRespType' => 'setNewOrderRespType',
        'sideEffectType' => 'setSideEffectType',
        'selfTradePreventionMode' => 'setSelfTradePreventionMode',
        'autoRepayAtCancel' => 'setAutoRepayAtCancel',
        'recvWindow' => 'setRecvWindow',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'symbol' => 'getSymbol',
        'isIsolated' => 'getIsIsolated',
        'listClientOrderId' => 'getListClientOrderId',
        'side' => 'getSide',
        'quantity' => 'getQuantity',
        'limitClientOrderId' => 'getLimitClientOrderId',
        'price' => 'getPrice',
        'limitIcebergQty' => 'getLimitIcebergQty',
        'stopClientOrderId' => 'getStopClientOrderId',
        'stopPrice' => 'getStopPrice',
        'stopLimitPrice' => 'getStopLimitPrice',
        'stopIcebergQty' => 'getStopIcebergQty',
        'stopLimitTimeInForce' => 'getStopLimitTimeInForce',
        'newOrderRespType' => 'getNewOrderRespType',
        'sideEffectType' => 'getSideEffectType',
        'selfTradePreventionMode' => 'getSelfTradePreventionMode',
        'autoRepayAtCancel' => 'getAutoRepayAtCancel',
        'recvWindow' => 'getRecvWindow',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param null|mixed[] $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('symbol', $data ?? [], null);
        $this->setIfExists('isIsolated', $data ?? [], null);
        $this->setIfExists('listClientOrderId', $data ?? [], null);
        $this->setIfExists('side', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('limitClientOrderId', $data ?? [], null);
        $this->setIfExists('price', $data ?? [], null);
        $this->setIfExists('limitIcebergQty', $data ?? [], null);
        $this->setIfExists('stopClientOrderId', $data ?? [], null);
        $this->setIfExists('stopPrice', $data ?? [], null);
        $this->setIfExists('stopLimitPrice', $data ?? [], null);
        $this->setIfExists('stopIcebergQty', $data ?? [], null);
        $this->setIfExists('stopLimitTimeInForce', $data ?? [], null);
        $this->setIfExists('newOrderRespType', $data ?? [], null);
        $this->setIfExists('sideEffectType', $data ?? [], null);
        $this->setIfExists('selfTradePreventionMode', $data ?? [], null);
        $this->setIfExists('autoRepayAtCancel', $data ?? [], null);
        $this->setIfExists('recvWindow', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * If oneOf schema, get the possible response types.
     */
    public static function getComposedSchemas(): array
    {
        return [
        ];
    }

    /**
     * Return true if the model is an array.
     */
    public static function isArray(): bool
    {
        return false;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (null === $this->container['symbol']) {
            $invalidProperties[] = "'symbol' can't be null";
        }
        if (null === $this->container['side']) {
            $invalidProperties[] = "'side' can't be null";
        }
        if (null === $this->container['quantity']) {
            $invalidProperties[] = "'quantity' can't be null";
        }
        if (null === $this->container['price']) {
            $invalidProperties[] = "'price' can't be null";
        }
        if (null === $this->container['stopPrice']) {
            $invalidProperties[] = "'stopPrice' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets symbol.
     *
     * @return string
     */
    public function getSymbol()
    {
        return $this->container['symbol'];
    }

    /**
     * Sets symbol.
     *
     * @param string $symbol symbol
     *
     * @return self
     */
    public function setSymbol($symbol)
    {
        if (is_null($symbol)) {
            throw new \InvalidArgumentException('non-nullable symbol cannot be null');
        }
        $this->container['symbol'] = $symbol;

        return $this;
    }

    /**
     * Gets isIsolated.
     *
     * @return null|string
     */
    public function getIsIsolated()
    {
        return $this->container['isIsolated'];
    }

    /**
     * Sets isIsolated.
     *
     * @param null|string $isIsolated isIsolated
     *
     * @return self
     */
    public function setIsIsolated($isIsolated)
    {
        if (is_null($isIsolated)) {
            throw new \InvalidArgumentException('non-nullable isIsolated cannot be null');
        }
        $this->container['isIsolated'] = $isIsolated;

        return $this;
    }

    /**
     * Gets listClientOrderId.
     *
     * @return null|string
     */
    public function getListClientOrderId()
    {
        return $this->container['listClientOrderId'];
    }

    /**
     * Sets listClientOrderId.
     *
     * @param null|string $listClientOrderId listClientOrderId
     *
     * @return self
     */
    public function setListClientOrderId($listClientOrderId)
    {
        if (is_null($listClientOrderId)) {
            throw new \InvalidArgumentException('non-nullable listClientOrderId cannot be null');
        }
        $this->container['listClientOrderId'] = $listClientOrderId;

        return $this;
    }

    /**
     * Gets side.
     *
     * @return Side
     */
    public function getSide()
    {
        return $this->container['side'];
    }

    /**
     * Sets side.
     *
     * @param Side $side side
     *
     * @return self
     */
    public function setSide($side)
    {
        if (is_null($side)) {
            throw new \InvalidArgumentException('non-nullable side cannot be null');
        }
        $this->container['side'] = $side;

        return $this;
    }

    /**
     * Gets quantity.
     *
     * @return float
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity.
     *
     * @param float $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            throw new \InvalidArgumentException('non-nullable quantity cannot be null');
        }
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets limitClientOrderId.
     *
     * @return null|string
     */
    public function getLimitClientOrderId()
    {
        return $this->container['limitClientOrderId'];
    }

    /**
     * Sets limitClientOrderId.
     *
     * @param null|string $limitClientOrderId limitClientOrderId
     *
     * @return self
     */
    public function setLimitClientOrderId($limitClientOrderId)
    {
        if (is_null($limitClientOrderId)) {
            throw new \InvalidArgumentException('non-nullable limitClientOrderId cannot be null');
        }
        $this->container['limitClientOrderId'] = $limitClientOrderId;

        return $this;
    }

    /**
     * Gets price.
     *
     * @return float
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price.
     *
     * @param float $price price
     *
     * @return self
     */
    public function setPrice($price)
    {
        if (is_null($price)) {
            throw new \InvalidArgumentException('non-nullable price cannot be null');
        }
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets limitIcebergQty.
     *
     * @return null|float
     */
    public function getLimitIcebergQty()
    {
        return $this->container['limitIcebergQty'];
    }

    /**
     * Sets limitIcebergQty.
     *
     * @param null|float $limitIcebergQty limitIcebergQty
     *
     * @return self
     */
    public function setLimitIcebergQty($limitIcebergQty)
    {
        if (is_null($limitIcebergQty)) {
            throw new \InvalidArgumentException('non-nullable limitIcebergQty cannot be null');
        }
        $this->container['limitIcebergQty'] = $limitIcebergQty;

        return $this;
    }

    /**
     * Gets stopClientOrderId.
     *
     * @return null|string
     */
    public function getStopClientOrderId()
    {
        return $this->container['stopClientOrderId'];
    }

    /**
     * Sets stopClientOrderId.
     *
     * @param null|string $stopClientOrderId stopClientOrderId
     *
     * @return self
     */
    public function setStopClientOrderId($stopClientOrderId)
    {
        if (is_null($stopClientOrderId)) {
            throw new \InvalidArgumentException('non-nullable stopClientOrderId cannot be null');
        }
        $this->container['stopClientOrderId'] = $stopClientOrderId;

        return $this;
    }

    /**
     * Gets stopPrice.
     *
     * @return float
     */
    public function getStopPrice()
    {
        return $this->container['stopPrice'];
    }

    /**
     * Sets stopPrice.
     *
     * @param float $stopPrice stopPrice
     *
     * @return self
     */
    public function setStopPrice($stopPrice)
    {
        if (is_null($stopPrice)) {
            throw new \InvalidArgumentException('non-nullable stopPrice cannot be null');
        }
        $this->container['stopPrice'] = $stopPrice;

        return $this;
    }

    /**
     * Gets stopLimitPrice.
     *
     * @return null|float
     */
    public function getStopLimitPrice()
    {
        return $this->container['stopLimitPrice'];
    }

    /**
     * Sets stopLimitPrice.
     *
     * @param null|float $stopLimitPrice stopLimitPrice
     *
     * @return self
     */
    public function setStopLimitPrice($stopLimitPrice)
    {
        if (is_null($stopLimitPrice)) {
            throw new \InvalidArgumentException('non-nullable stopLimitPrice cannot be null');
        }
        $this->container['stopLimitPrice'] = $stopLimitPrice;

        return $this;
    }

    /**
     * Gets stopIcebergQty.
     *
     * @return null|float
     */
    public function getStopIcebergQty()
    {
        return $this->container['stopIcebergQty'];
    }

    /**
     * Sets stopIcebergQty.
     *
     * @param null|float $stopIcebergQty stopIcebergQty
     *
     * @return self
     */
    public function setStopIcebergQty($stopIcebergQty)
    {
        if (is_null($stopIcebergQty)) {
            throw new \InvalidArgumentException('non-nullable stopIcebergQty cannot be null');
        }
        $this->container['stopIcebergQty'] = $stopIcebergQty;

        return $this;
    }

    /**
     * Gets stopLimitTimeInForce.
     *
     * @return null|string
     */
    public function getStopLimitTimeInForce()
    {
        return $this->container['stopLimitTimeInForce'];
    }

    /**
     * Sets stopLimitTimeInForce.
     *
     * @param null|string $stopLimitTimeInForce stopLimitTimeInForce
     *
     * @return self
     */
    public function setStopLimitTimeInForce($stopLimitTimeInForce)
    {
        if (is_null($stopLimitTimeInForce)) {
            throw new \InvalidArgumentException('non-nullable stopLimitTimeInForce cannot be null');
        }
        $this->container['stopLimitTimeInForce'] = $stopLimitTimeInForce;

        return $this;
    }

    /**
     * Gets newOrderRespType.
     *
     * @return null|NewOrderRespType
     */
    public function getNewOrderRespType()
    {
        return $this->container['newOrderRespType'];
    }

    /**
     * Sets newOrderRespType.
     *
     * @param null|NewOrderRespType $newOrderRespType newOrderRespType
     *
     * @return self
     */
    public function setNewOrderRespType($newOrderRespType)
    {
        if (is_null($newOrderRespType)) {
            throw new \InvalidArgumentException('non-nullable newOrderRespType cannot be null');
        }
        $this->container['newOrderRespType'] = $newOrderRespType;

        return $this;
    }

    /**
     * Gets sideEffectType.
     *
     * @return null|string
     */
    public function getSideEffectType()
    {
        return $this->container['sideEffectType'];
    }

    /**
     * Sets sideEffectType.
     *
     * @param null|string $sideEffectType sideEffectType
     *
     * @return self
     */
    public function setSideEffectType($sideEffectType)
    {
        if (is_null($sideEffectType)) {
            throw new \InvalidArgumentException('non-nullable sideEffectType cannot be null');
        }
        $this->container['sideEffectType'] = $sideEffectType;

        return $this;
    }

    /**
     * Gets selfTradePreventionMode.
     *
     * @return null|string
     */
    public function getSelfTradePreventionMode()
    {
        return $this->container['selfTradePreventionMode'];
    }

    /**
     * Sets selfTradePreventionMode.
     *
     * @param null|string $selfTradePreventionMode selfTradePreventionMode
     *
     * @return self
     */
    public function setSelfTradePreventionMode($selfTradePreventionMode)
    {
        if (is_null($selfTradePreventionMode)) {
            throw new \InvalidArgumentException('non-nullable selfTradePreventionMode cannot be null');
        }
        $this->container['selfTradePreventionMode'] = $selfTradePreventionMode;

        return $this;
    }

    /**
     * Gets autoRepayAtCancel.
     *
     * @return null|bool
     */
    public function getAutoRepayAtCancel()
    {
        return $this->container['autoRepayAtCancel'];
    }

    /**
     * Sets autoRepayAtCancel.
     *
     * @param null|bool $autoRepayAtCancel autoRepayAtCancel
     *
     * @return self
     */
    public function setAutoRepayAtCancel($autoRepayAtCancel)
    {
        if (is_null($autoRepayAtCancel)) {
            throw new \InvalidArgumentException('non-nullable autoRepayAtCancel cannot be null');
        }
        $this->container['autoRepayAtCancel'] = $autoRepayAtCancel;

        return $this;
    }

    /**
     * Gets recvWindow.
     *
     * @return null|int
     */
    public function getRecvWindow()
    {
        return $this->container['recvWindow'];
    }

    /**
     * Sets recvWindow.
     *
     * @param null|int $recvWindow recvWindow
     *
     * @return self
     */
    public function setRecvWindow($recvWindow)
    {
        if (is_null($recvWindow)) {
            throw new \InvalidArgumentException('non-nullable recvWindow cannot be null');
        }
        $this->container['recvWindow'] = $recvWindow;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
