<?php

/**
 * MarketDataApiTest
 * PHP version 8.1.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Binance VIP Loan REST API.
 *
 * OpenAPI Specification for the Binance VIP Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Binance\Client\VipLoan\Test\Api;

use Binance\Client\VipLoan\Api\MarketDataApi;
use Binance\Common\Configuration\ClientConfiguration;
use Binance\Common\Configuration\SignatureConfiguration;
use Binance\Common\HttpClient;
use GuzzleHttp\Psr7\Utils;
use PHPUnit\Framework\TestCase;
use Psr\Http\Message\ResponseInterface;

/**
 * MarketDataApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @internal
 *
 * @coversNothing
 */
class MarketDataApiTest extends TestCase
{
    public function getApiMock(&$request)
    {
        $clientMock = $this->createMock(HttpClient::class);
        $signatureConfig = new SignatureConfiguration();
        $signatureConfig->setApiKey('apiKey');
        $signatureConfig->setSecretKey('secretKey');
        $clientConfig = new ClientConfiguration();
        $clientConfig->setUrl('http://localhost:8080');
        $clientConfig->setSignatureConfiguration($signatureConfig);
        $responseMock = $this->createMock(ResponseInterface::class);

        $responseMock->expects($this->any())
            ->method('getStatusCode')
            ->willReturn(200)
        ;

        $responseMock->expects($this->any())
            ->method('getBody')
            ->willReturn(Utils::streamFor('{}'))
        ;

        $clientMock->expects($this->once())
            ->method('send')
            ->will($this->returnCallback(function ($actualRequest) use (&$request, $responseMock) {
                $request = $actualRequest;

                return $responseMock;
            }))
        ;

        $apiMock = $this->getMockBuilder(MarketDataApi::class)
            ->setConstructorArgs([$clientConfig, $clientMock])
            ->onlyMethods(['getTimestamp'])
            ->getMock()
        ;

        $apiMock->method('getTimestamp')->willReturn('1736393892000');

        return $apiMock;
    }

    /**
     * Test case for getBorrowInterestRate.
     *
     * Get Borrow Interest Rate(USER_DATA).
     */
    public function testGetBorrowInterestRate()
    {
        $loanCoin = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getBorrowInterestRate($loanCoin, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/loan/vip/request/interestRate', $request->getUri()->getPath());
        self::assertEquals('2a09517b57df001aaf35228b8642b62271321de1e3714ccb1f56606355218630', $queryMap['signature']);
    }

    /**
     * Test case for getCollateralAssetData.
     *
     * Get Collateral Asset Data(USER_DATA).
     */
    public function testGetCollateralAssetData()
    {
        $collateralCoin = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getCollateralAssetData($collateralCoin, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/loan/vip/collateral/data', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for getLoanableAssetsData.
     *
     * Get Loanable Assets Data(USER_DATA).
     */
    public function testGetLoanableAssetsData()
    {
        $loanCoin = '';
        $vipLevel = 1;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getLoanableAssetsData($loanCoin, $vipLevel, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/loan/vip/loanable/data', $request->getUri()->getPath());
        self::assertEquals('a62fe6f3ebcc76daa42cdbc545942422a6a55499946c0d5a642a1f6457231173', $queryMap['signature']);
    }

    /**
     * Test case for getVIPLoanInterestRateHistory.
     *
     * Get VIP Loan Interest Rate History (USER_DATA).
     */
    public function testGetVIPLoanInterestRateHistory()
    {
        $coin = '';
        $recvWindow = 5000;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $current = 1;
        $limit = 10;
        $response = $this->getApiMock($request)->getVIPLoanInterestRateHistory($coin, $recvWindow, $startTime, $endTime, $current, $limit);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/sapi/v1/loan/vip/interestRateHistory', $request->getUri()->getPath());
        self::assertEquals('72cd0355d89715dad29de1cd1a2f5810a0691c37c444344d80894c742be1bd62', $queryMap['signature']);
    }
}
