<?php

/**
 * VipLoanBorrowRequest.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Binance VIP Loan REST API.
 *
 * OpenAPI Specification for the Binance VIP Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Binance\Client\VipLoan\Model;

use Binance\Common\Dtos\ModelInterface;
use Binance\Common\ObjectSerializer;

/**
 * VipLoanBorrowRequest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class VipLoanBorrowRequest implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'vipLoanBorrowRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'loanAccountId' => 'int',
        'loanCoin' => 'string',
        'loanAmount' => 'float',
        'collateralAccountId' => 'int',
        'collateralCoin' => 'string',
        'isFlexibleRate' => 'bool',
        'loanTerm' => 'int',
        'recvWindow' => 'int',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'loanAccountId' => 'int64',
        'loanCoin' => null,
        'loanAmount' => 'float',
        'collateralAccountId' => 'int64',
        'collateralCoin' => null,
        'isFlexibleRate' => null,
        'loanTerm' => 'int64',
        'recvWindow' => 'int64',
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'loanAccountId' => false,
        'loanCoin' => false,
        'loanAmount' => false,
        'collateralAccountId' => false,
        'collateralCoin' => false,
        'isFlexibleRate' => false,
        'loanTerm' => false,
        'recvWindow' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'loanAccountId' => 'loanAccountId',
        'loanCoin' => 'loanCoin',
        'loanAmount' => 'loanAmount',
        'collateralAccountId' => 'collateralAccountId',
        'collateralCoin' => 'collateralCoin',
        'isFlexibleRate' => 'isFlexibleRate',
        'loanTerm' => 'loanTerm',
        'recvWindow' => 'recvWindow',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'loanAccountId' => 'setLoanAccountId',
        'loanCoin' => 'setLoanCoin',
        'loanAmount' => 'setLoanAmount',
        'collateralAccountId' => 'setCollateralAccountId',
        'collateralCoin' => 'setCollateralCoin',
        'isFlexibleRate' => 'setIsFlexibleRate',
        'loanTerm' => 'setLoanTerm',
        'recvWindow' => 'setRecvWindow',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'loanAccountId' => 'getLoanAccountId',
        'loanCoin' => 'getLoanCoin',
        'loanAmount' => 'getLoanAmount',
        'collateralAccountId' => 'getCollateralAccountId',
        'collateralCoin' => 'getCollateralCoin',
        'isFlexibleRate' => 'getIsFlexibleRate',
        'loanTerm' => 'getLoanTerm',
        'recvWindow' => 'getRecvWindow',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param null|mixed[] $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('loanAccountId', $data ?? [], null);
        $this->setIfExists('loanCoin', $data ?? [], null);
        $this->setIfExists('loanAmount', $data ?? [], null);
        $this->setIfExists('collateralAccountId', $data ?? [], null);
        $this->setIfExists('collateralCoin', $data ?? [], null);
        $this->setIfExists('isFlexibleRate', $data ?? [], null);
        $this->setIfExists('loanTerm', $data ?? [], null);
        $this->setIfExists('recvWindow', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * If oneOf schema, get the possible response types.
     */
    public static function getComposedSchemas(): array
    {
        return [
        ];
    }

    /**
     * Return true if the model is an array.
     */
    public static function isArray(): bool
    {
        return false;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (null === $this->container['loanAccountId']) {
            $invalidProperties[] = "'loanAccountId' can't be null";
        }
        if (null === $this->container['loanCoin']) {
            $invalidProperties[] = "'loanCoin' can't be null";
        }
        if (null === $this->container['loanAmount']) {
            $invalidProperties[] = "'loanAmount' can't be null";
        }
        if (null === $this->container['collateralAccountId']) {
            $invalidProperties[] = "'collateralAccountId' can't be null";
        }
        if (null === $this->container['collateralCoin']) {
            $invalidProperties[] = "'collateralCoin' can't be null";
        }
        if (null === $this->container['isFlexibleRate']) {
            $invalidProperties[] = "'isFlexibleRate' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets loanAccountId.
     *
     * @return int
     */
    public function getLoanAccountId()
    {
        return $this->container['loanAccountId'];
    }

    /**
     * Sets loanAccountId.
     *
     * @param int $loanAccountId loanAccountId
     *
     * @return self
     */
    public function setLoanAccountId($loanAccountId)
    {
        if (is_null($loanAccountId)) {
            throw new \InvalidArgumentException('non-nullable loanAccountId cannot be null');
        }
        $this->container['loanAccountId'] = $loanAccountId;

        return $this;
    }

    /**
     * Gets loanCoin.
     *
     * @return string
     */
    public function getLoanCoin()
    {
        return $this->container['loanCoin'];
    }

    /**
     * Sets loanCoin.
     *
     * @param string $loanCoin loanCoin
     *
     * @return self
     */
    public function setLoanCoin($loanCoin)
    {
        if (is_null($loanCoin)) {
            throw new \InvalidArgumentException('non-nullable loanCoin cannot be null');
        }
        $this->container['loanCoin'] = $loanCoin;

        return $this;
    }

    /**
     * Gets loanAmount.
     *
     * @return float
     */
    public function getLoanAmount()
    {
        return $this->container['loanAmount'];
    }

    /**
     * Sets loanAmount.
     *
     * @param float $loanAmount loanAmount
     *
     * @return self
     */
    public function setLoanAmount($loanAmount)
    {
        if (is_null($loanAmount)) {
            throw new \InvalidArgumentException('non-nullable loanAmount cannot be null');
        }
        $this->container['loanAmount'] = $loanAmount;

        return $this;
    }

    /**
     * Gets collateralAccountId.
     *
     * @return int
     */
    public function getCollateralAccountId()
    {
        return $this->container['collateralAccountId'];
    }

    /**
     * Sets collateralAccountId.
     *
     * @param int $collateralAccountId collateralAccountId
     *
     * @return self
     */
    public function setCollateralAccountId($collateralAccountId)
    {
        if (is_null($collateralAccountId)) {
            throw new \InvalidArgumentException('non-nullable collateralAccountId cannot be null');
        }
        $this->container['collateralAccountId'] = $collateralAccountId;

        return $this;
    }

    /**
     * Gets collateralCoin.
     *
     * @return string
     */
    public function getCollateralCoin()
    {
        return $this->container['collateralCoin'];
    }

    /**
     * Sets collateralCoin.
     *
     * @param string $collateralCoin collateralCoin
     *
     * @return self
     */
    public function setCollateralCoin($collateralCoin)
    {
        if (is_null($collateralCoin)) {
            throw new \InvalidArgumentException('non-nullable collateralCoin cannot be null');
        }
        $this->container['collateralCoin'] = $collateralCoin;

        return $this;
    }

    /**
     * Gets isFlexibleRate.
     *
     * @return bool
     */
    public function getIsFlexibleRate()
    {
        return $this->container['isFlexibleRate'];
    }

    /**
     * Sets isFlexibleRate.
     *
     * @param bool $isFlexibleRate isFlexibleRate
     *
     * @return self
     */
    public function setIsFlexibleRate($isFlexibleRate)
    {
        if (is_null($isFlexibleRate)) {
            throw new \InvalidArgumentException('non-nullable isFlexibleRate cannot be null');
        }
        $this->container['isFlexibleRate'] = $isFlexibleRate;

        return $this;
    }

    /**
     * Gets loanTerm.
     *
     * @return null|int
     */
    public function getLoanTerm()
    {
        return $this->container['loanTerm'];
    }

    /**
     * Sets loanTerm.
     *
     * @param null|int $loanTerm loanTerm
     *
     * @return self
     */
    public function setLoanTerm($loanTerm)
    {
        if (is_null($loanTerm)) {
            throw new \InvalidArgumentException('non-nullable loanTerm cannot be null');
        }
        $this->container['loanTerm'] = $loanTerm;

        return $this;
    }

    /**
     * Gets recvWindow.
     *
     * @return null|int
     */
    public function getRecvWindow()
    {
        return $this->container['recvWindow'];
    }

    /**
     * Sets recvWindow.
     *
     * @param null|int $recvWindow recvWindow
     *
     * @return self
     */
    public function setRecvWindow($recvWindow)
    {
        if (is_null($recvWindow)) {
            throw new \InvalidArgumentException('non-nullable recvWindow cannot be null');
        }
        $this->container['recvWindow'] = $recvWindow;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
