<?php

/**
 * VipLoanRepayResponse.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Binance VIP Loan REST API.
 *
 * OpenAPI Specification for the Binance VIP Loan REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Binance\Client\VipLoan\Model;

use Binance\Common\Dtos\ModelInterface;
use Binance\Common\ObjectSerializer;

/**
 * VipLoanRepayResponse Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @implements \ArrayAccess<string, mixed>
 */
class VipLoanRepayResponse implements ModelInterface, \ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'vipLoanRepayResponse';

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'loanCoin' => 'string',
        'repayAmount' => 'string',
        'remainingPrincipal' => 'string',
        'remainingInterest' => 'string',
        'collateralCoin' => 'string',
        'currentLTV' => 'string',
        'repayStatus' => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @var string[]
     *
     * @phpstan-var array<string, string|null>
     *
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'loanCoin' => null,
        'repayAmount' => null,
        'remainingPrincipal' => null,
        'remainingInterest' => null,
        'collateralCoin' => null,
        'currentLTV' => null,
        'repayStatus' => null,
    ];

    /**
     * Array of nullable properties. Used for (de)serialization.
     *
     * @var bool[]
     */
    protected static array $openAPINullables = [
        'loanCoin' => false,
        'repayAmount' => false,
        'remainingPrincipal' => false,
        'remainingInterest' => false,
        'collateralCoin' => false,
        'currentLTV' => false,
        'repayStatus' => false,
    ];

    /**
     * If a nullable field gets set to null, insert it here.
     *
     * @var bool[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'loanCoin' => 'loanCoin',
        'repayAmount' => 'repayAmount',
        'remainingPrincipal' => 'remainingPrincipal',
        'remainingInterest' => 'remainingInterest',
        'collateralCoin' => 'collateralCoin',
        'currentLTV' => 'currentLTV',
        'repayStatus' => 'repayStatus',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @var string[]
     */
    protected static $setters = [
        'loanCoin' => 'setLoanCoin',
        'repayAmount' => 'setRepayAmount',
        'remainingPrincipal' => 'setRemainingPrincipal',
        'remainingInterest' => 'setRemainingInterest',
        'collateralCoin' => 'setCollateralCoin',
        'currentLTV' => 'setCurrentLTV',
        'repayStatus' => 'setRepayStatus',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @var string[]
     */
    protected static $getters = [
        'loanCoin' => 'getLoanCoin',
        'repayAmount' => 'getRepayAmount',
        'remainingPrincipal' => 'getRemainingPrincipal',
        'remainingInterest' => 'getRemainingInterest',
        'collateralCoin' => 'getCollateralCoin',
        'currentLTV' => 'getCurrentLTV',
        'repayStatus' => 'getRepayStatus',
    ];

    /**
     * Associative array for storing property values.
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor.
     *
     * @param null|mixed[] $data Associated array of property values
     *                           initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('loanCoin', $data ?? [], null);
        $this->setIfExists('repayAmount', $data ?? [], null);
        $this->setIfExists('remainingPrincipal', $data ?? [], null);
        $this->setIfExists('remainingInterest', $data ?? [], null);
        $this->setIfExists('collateralCoin', $data ?? [], null);
        $this->setIfExists('currentLTV', $data ?? [], null);
        $this->setIfExists('repayStatus', $data ?? [], null);
    }

    /**
     * Gets the string presentation of the object.
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Array of property to type mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization.
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * If oneOf schema, get the possible response types.
     */
    public static function getComposedSchemas(): array
    {
        return [
        ];
    }

    /**
     * Return true if the model is an array.
     */
    public static function isArray(): bool
    {
        return false;
    }

    /**
     * Checks if a property is nullable.
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name.
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses).
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests).
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        return [];
    }

    /**
     * Validate all the properties in the model
     * return true if all passed.
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return 0 === count($this->listInvalidProperties());
    }

    /**
     * Gets loanCoin.
     *
     * @return null|string
     */
    public function getLoanCoin()
    {
        return $this->container['loanCoin'];
    }

    /**
     * Sets loanCoin.
     *
     * @param null|string $loanCoin loanCoin
     *
     * @return self
     */
    public function setLoanCoin($loanCoin)
    {
        if (is_null($loanCoin)) {
            throw new \InvalidArgumentException('non-nullable loanCoin cannot be null');
        }
        $this->container['loanCoin'] = $loanCoin;

        return $this;
    }

    /**
     * Gets repayAmount.
     *
     * @return null|string
     */
    public function getRepayAmount()
    {
        return $this->container['repayAmount'];
    }

    /**
     * Sets repayAmount.
     *
     * @param null|string $repayAmount repayAmount
     *
     * @return self
     */
    public function setRepayAmount($repayAmount)
    {
        if (is_null($repayAmount)) {
            throw new \InvalidArgumentException('non-nullable repayAmount cannot be null');
        }
        $this->container['repayAmount'] = $repayAmount;

        return $this;
    }

    /**
     * Gets remainingPrincipal.
     *
     * @return null|string
     */
    public function getRemainingPrincipal()
    {
        return $this->container['remainingPrincipal'];
    }

    /**
     * Sets remainingPrincipal.
     *
     * @param null|string $remainingPrincipal remainingPrincipal
     *
     * @return self
     */
    public function setRemainingPrincipal($remainingPrincipal)
    {
        if (is_null($remainingPrincipal)) {
            throw new \InvalidArgumentException('non-nullable remainingPrincipal cannot be null');
        }
        $this->container['remainingPrincipal'] = $remainingPrincipal;

        return $this;
    }

    /**
     * Gets remainingInterest.
     *
     * @return null|string
     */
    public function getRemainingInterest()
    {
        return $this->container['remainingInterest'];
    }

    /**
     * Sets remainingInterest.
     *
     * @param null|string $remainingInterest remainingInterest
     *
     * @return self
     */
    public function setRemainingInterest($remainingInterest)
    {
        if (is_null($remainingInterest)) {
            throw new \InvalidArgumentException('non-nullable remainingInterest cannot be null');
        }
        $this->container['remainingInterest'] = $remainingInterest;

        return $this;
    }

    /**
     * Gets collateralCoin.
     *
     * @return null|string
     */
    public function getCollateralCoin()
    {
        return $this->container['collateralCoin'];
    }

    /**
     * Sets collateralCoin.
     *
     * @param null|string $collateralCoin collateralCoin
     *
     * @return self
     */
    public function setCollateralCoin($collateralCoin)
    {
        if (is_null($collateralCoin)) {
            throw new \InvalidArgumentException('non-nullable collateralCoin cannot be null');
        }
        $this->container['collateralCoin'] = $collateralCoin;

        return $this;
    }

    /**
     * Gets currentLTV.
     *
     * @return null|string
     */
    public function getCurrentLTV()
    {
        return $this->container['currentLTV'];
    }

    /**
     * Sets currentLTV.
     *
     * @param null|string $currentLTV currentLTV
     *
     * @return self
     */
    public function setCurrentLTV($currentLTV)
    {
        if (is_null($currentLTV)) {
            throw new \InvalidArgumentException('non-nullable currentLTV cannot be null');
        }
        $this->container['currentLTV'] = $currentLTV;

        return $this;
    }

    /**
     * Gets repayStatus.
     *
     * @return null|string
     */
    public function getRepayStatus()
    {
        return $this->container['repayStatus'];
    }

    /**
     * Sets repayStatus.
     *
     * @param null|string $repayStatus repayStatus
     *
     * @return self
     */
    public function setRepayStatus($repayStatus)
    {
        if (is_null($repayStatus)) {
            throw new \InvalidArgumentException('non-nullable repayStatus cannot be null');
        }
        $this->container['repayStatus'] = $repayStatus;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return null|mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param null|int $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     *
     * @see https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed returns data which can be serialized by json_encode(), which is a value
     *               of any type other than a resource
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets a header-safe presentation of the object.
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

    /**
     * Array of nullable properties.
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null.
     *
     * @return bool[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null.
     *
     * @param bool[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array.
     *
     * @param mixed $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }
}
