<?php

/**
 * WorkingType.
 *
 * PHP version 8.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Futures (COIN-M) REST API.
 *
 * Access market data, manage accounts, and trade COIN-M perpetual and delivery futures.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Binance\Client\DerivativesTradingCoinFutures\Model;

/**
 * WorkingType Class Doc Comment.
 *
 * @category Class
 *
 * @description &#39;stopPrice triggered by: \&quot;MARK_PRICE\&quot;, \&quot;CONTRACT_PRICE\&quot;.
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */
enum WorkingType: string
{
    /**
     * Possible values of this enum.
     */
    case MARK_PRICE = 'MARK_PRICE';

    case CONTRACT_PRICE = 'CONTRACT_PRICE';

    /**
     * Gets allowable values of the enum.
     *
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MARK_PRICE,
            self::CONTRACT_PRICE,
        ];
    }
}
