<?php

/**
 * TradeApiTest
 * PHP version 8.1.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 */

/**
 * Binance Derivatives Trading USDS Futures REST API.
 *
 * OpenAPI Specification for the Binance Derivatives Trading USDS Futures REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Binance\Client\DerivativesTradingUsdsFutures\Test\Api;

use Binance\Client\DerivativesTradingUsdsFutures\Api\TradeApi;
use Binance\Client\DerivativesTradingUsdsFutures\Model\AutoCancelAllOpenOrdersRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\AutoCloseType;
use Binance\Client\DerivativesTradingUsdsFutures\Model\BatchOrders;
use Binance\Client\DerivativesTradingUsdsFutures\Model\BatchOrdersPlaceMultipleOrders;
use Binance\Client\DerivativesTradingUsdsFutures\Model\ChangeInitialLeverageRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\ChangeMarginTypeRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\ChangeMultiAssetsModeRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\ChangePositionModeRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\FuturesTradfiPerpsContractRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\MarginType;
use Binance\Client\DerivativesTradingUsdsFutures\Model\ModifyIsolatedPositionMarginRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\ModifyMultipleOrdersRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\ModifyOrderRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\NewAlgoOrderRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\NewOrderRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\PlaceMultipleOrdersRequest;
use Binance\Client\DerivativesTradingUsdsFutures\Model\Side;
use Binance\Client\DerivativesTradingUsdsFutures\Model\TestOrderRequest;
use Binance\Common\Configuration\ClientConfiguration;
use Binance\Common\Configuration\SignatureConfiguration;
use Binance\Common\HttpClient;
use GuzzleHttp\Psr7\Utils;
use PHPUnit\Framework\TestCase;
use Psr\Http\Message\ResponseInterface;

/**
 * TradeApiTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://openapi-generator.tech
 *
 * @internal
 *
 * @coversNothing
 */
class TradeApiTest extends TestCase
{
    public function getApiMock(&$request)
    {
        $clientMock = $this->createMock(HttpClient::class);
        $signatureConfig = new SignatureConfiguration();
        $signatureConfig->setApiKey('apiKey');
        $signatureConfig->setSecretKey('secretKey');
        $clientConfig = new ClientConfiguration();
        $clientConfig->setUrl('http://localhost:8080');
        $clientConfig->setSignatureConfiguration($signatureConfig);
        $responseMock = $this->createMock(ResponseInterface::class);

        $responseMock->expects($this->any())
            ->method('getStatusCode')
            ->willReturn(200)
        ;

        $responseMock->expects($this->any())
            ->method('getBody')
            ->willReturn(Utils::streamFor('{}'))
        ;

        $clientMock->expects($this->once())
            ->method('send')
            ->will($this->returnCallback(function ($actualRequest) use (&$request, $responseMock) {
                $request = $actualRequest;

                return $responseMock;
            }))
        ;

        $apiMock = $this->getMockBuilder(TradeApi::class)
            ->setConstructorArgs([$clientConfig, $clientMock])
            ->onlyMethods(['getTimestamp'])
            ->getMock()
        ;

        $apiMock->method('getTimestamp')->willReturn('1736393892000');

        return $apiMock;
    }

    /**
     * Test case for accountTradeList.
     *
     * Account Trade List (USER_DATA).
     */
    public function testAccountTradeList()
    {
        $symbol = '';
        $orderId = 1;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $fromId = 1;
        $limit = 100;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->accountTradeList($symbol, $orderId, $startTime, $endTime, $fromId, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/userTrades', $request->getUri()->getPath());
        self::assertEquals('10058794572cc782968aa3d3e6b73a369146898e471235e8712344dea70cb4d5', $queryMap['signature']);
    }

    /**
     * Test case for allOrders.
     *
     * All Orders (USER_DATA).
     */
    public function testAllOrders()
    {
        $symbol = '';
        $orderId = 1;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $limit = 100;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->allOrders($symbol, $orderId, $startTime, $endTime, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/allOrders', $request->getUri()->getPath());
        self::assertEquals('dc0808314025fc813dcde0328cd6754c982d28888760fc74b17e072087eb4895', $queryMap['signature']);
    }

    /**
     * Test case for autoCancelAllOpenOrders.
     *
     * Auto-Cancel All Open Orders (TRADE).
     */
    public function testAutoCancelAllOpenOrders()
    {
        $autoCancelAllOpenOrdersRequest = new AutoCancelAllOpenOrdersRequest();
        $autoCancelAllOpenOrdersRequest->setSymbol('');
        $autoCancelAllOpenOrdersRequest->setCountdownTime(1);

        $response = $this->getApiMock($request)->autoCancelAllOpenOrders($autoCancelAllOpenOrdersRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/countdownCancelAll', $request->getUri()->getPath());
        self::assertEquals('ffeb79f9ed5e4cabe07e39725c15ed03fad830cb2a86d4aae1b7081c89aa7150', $queryMap['signature']);
    }

    /**
     * Test case for cancelAlgoOrder.
     *
     * Cancel Algo Order (TRADE).
     */
    public function testCancelAlgoOrder()
    {
        $algoid = null;
        $clientalgoid = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->cancelAlgoOrder($algoid, $clientalgoid, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/algoOrder', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for cancelAllAlgoOpenOrders.
     *
     * Cancel All Algo Open Orders (TRADE).
     */
    public function testCancelAllAlgoOpenOrders()
    {
        $symbol = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->cancelAllAlgoOpenOrders($symbol, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/algoOpenOrders', $request->getUri()->getPath());
        self::assertEquals('db1a455af0a2e82b4ec79595d994eb2e7f6b8a93c91a67a2aa59e2b2eae4bc68', $queryMap['signature']);
    }

    /**
     * Test case for cancelAllOpenOrders.
     *
     * Cancel All Open Orders (TRADE).
     */
    public function testCancelAllOpenOrders()
    {
        $symbol = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->cancelAllOpenOrders($symbol, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/allOpenOrders', $request->getUri()->getPath());
        self::assertEquals('db1a455af0a2e82b4ec79595d994eb2e7f6b8a93c91a67a2aa59e2b2eae4bc68', $queryMap['signature']);
    }

    /**
     * Test case for cancelMultipleOrders.
     *
     * Cancel Multiple Orders (TRADE).
     */
    public function testCancelMultipleOrders()
    {
        $symbol = '';
        $orderIdList = null;
        $origClientOrderIdList = null;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->cancelMultipleOrders($symbol, $orderIdList, $origClientOrderIdList, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/batchOrders', $request->getUri()->getPath());
        self::assertEquals('db1a455af0a2e82b4ec79595d994eb2e7f6b8a93c91a67a2aa59e2b2eae4bc68', $queryMap['signature']);
    }

    /**
     * Test case for cancelOrder.
     *
     * Cancel Order (TRADE).
     */
    public function testCancelOrder()
    {
        $symbol = '';
        $orderId = 1;
        $origClientOrderId = '1';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->cancelOrder($symbol, $orderId, $origClientOrderId, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/order', $request->getUri()->getPath());
        self::assertEquals('cbec82483be2ad044b893ffb2e6bc0d55370e378eaea0b4b61d95893bd9cc458', $queryMap['signature']);
    }

    /**
     * Test case for changeInitialLeverage.
     *
     * Change Initial Leverage(TRADE).
     */
    public function testChangeInitialLeverage()
    {
        $changeInitialLeverageRequest = new ChangeInitialLeverageRequest();
        $changeInitialLeverageRequest->setSymbol('');
        $changeInitialLeverageRequest->setLeverage(1);

        $response = $this->getApiMock($request)->changeInitialLeverage($changeInitialLeverageRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/leverage', $request->getUri()->getPath());
        self::assertEquals('c4732c9aa613aa34fafed94623554e163fd7c8b28d8b2cefc5a265dc69f45056', $queryMap['signature']);
    }

    /**
     * Test case for changeMarginType.
     *
     * Change Margin Type(TRADE).
     */
    public function testChangeMarginType()
    {
        $changeMarginTypeRequest = new ChangeMarginTypeRequest();
        $changeMarginTypeRequest->setSymbol('');
        $changeMarginTypeRequest->setMarginType(MarginType::ISOLATED);

        $response = $this->getApiMock($request)->changeMarginType($changeMarginTypeRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/marginType', $request->getUri()->getPath());
        self::assertEquals('c6a0dc5b9b317f83930d8a753bedb1cc344d3a2ccb88b1139c71703f6efcb7c9', $queryMap['signature']);
    }

    /**
     * Test case for changeMultiAssetsMode.
     *
     * Change Multi-Assets Mode (TRADE).
     */
    public function testChangeMultiAssetsMode()
    {
        $changeMultiAssetsModeRequest = new ChangeMultiAssetsModeRequest();
        $changeMultiAssetsModeRequest->setMultiAssetsMargin('');

        $response = $this->getApiMock($request)->changeMultiAssetsMode($changeMultiAssetsModeRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/multiAssetsMargin', $request->getUri()->getPath());
        self::assertEquals('8236637257ef770fc34031243fd786e85b0f01fbea5f83a83b6421a1df3b6319', $queryMap['signature']);
    }

    /**
     * Test case for changePositionMode.
     *
     * Change Position Mode(TRADE).
     */
    public function testChangePositionMode()
    {
        $changePositionModeRequest = new ChangePositionModeRequest();
        $changePositionModeRequest->setDualSidePosition('');

        $response = $this->getApiMock($request)->changePositionMode($changePositionModeRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/positionSide/dual', $request->getUri()->getPath());
        self::assertEquals('bebef105cea3efc7f04654c618d2083229fcfc36b20173f0634e17be5042abd9', $queryMap['signature']);
    }

    /**
     * Test case for currentAllAlgoOpenOrders.
     *
     * Current All Algo Open Orders (USER_DATA).
     */
    public function testCurrentAllAlgoOpenOrders()
    {
        $algoType = '';
        $symbol = '';
        $algoId = 1;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->currentAllAlgoOpenOrders($algoType, $symbol, $algoId, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/openAlgoOrders', $request->getUri()->getPath());
        self::assertEquals('4dcc675276dcc7a5eddf3f11f98e221dc22b447b227be14ec73a51c61602f2a5', $queryMap['signature']);
    }

    /**
     * Test case for currentAllOpenOrders.
     *
     * Current All Open Orders (USER_DATA).
     */
    public function testCurrentAllOpenOrders()
    {
        $symbol = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->currentAllOpenOrders($symbol, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/openOrders', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for futuresTradfiPerpsContract.
     *
     * Futures TradFi Perps Contract(USER_DATA).
     */
    public function testFuturesTradfiPerpsContract()
    {
        $futuresTradfiPerpsContractRequest = new FuturesTradfiPerpsContractRequest();

        $response = $this->getApiMock($request)->futuresTradfiPerpsContract($futuresTradfiPerpsContractRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/stock/contract', $request->getUri()->getPath());
        self::assertEquals('dc0def720e795be0f84b02a8fa211ecc3a27dd06ffdbd287a679f1321807f820', $queryMap['signature']);
    }

    /**
     * Test case for getOrderModifyHistory.
     *
     * Get Order Modify History (USER_DATA).
     */
    public function testGetOrderModifyHistory()
    {
        $symbol = '';
        $orderId = 1;
        $origClientOrderId = '1';
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $limit = 100;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getOrderModifyHistory($symbol, $orderId, $origClientOrderId, $startTime, $endTime, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/orderAmendment', $request->getUri()->getPath());
        self::assertEquals('8dfcc843fc05f631a3b12c4a0080f9d1f2283472ee0032b3e7e7fd46d855bcde', $queryMap['signature']);
    }

    /**
     * Test case for getPositionMarginChangeHistory.
     *
     * Get Position Margin Change History (TRADE).
     */
    public function testGetPositionMarginChangeHistory()
    {
        $symbol = '';
        $type = '';
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $limit = 100;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->getPositionMarginChangeHistory($symbol, $type, $startTime, $endTime, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/positionMargin/history', $request->getUri()->getPath());
        self::assertEquals('3d9795ecfdb1326d191e1c4777f0f21d3abe1b7efbde9431ba818a057bd1dd7f', $queryMap['signature']);
    }

    /**
     * Test case for modifyIsolatedPositionMargin.
     *
     * Modify Isolated Position Margin(TRADE).
     */
    public function testModifyIsolatedPositionMargin()
    {
        $modifyIsolatedPositionMarginRequest = new ModifyIsolatedPositionMarginRequest();
        $modifyIsolatedPositionMarginRequest->setSymbol('');
        $modifyIsolatedPositionMarginRequest->setAmount(1.0);
        $modifyIsolatedPositionMarginRequest->setType('');

        $response = $this->getApiMock($request)->modifyIsolatedPositionMargin($modifyIsolatedPositionMarginRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/positionMargin', $request->getUri()->getPath());
        self::assertEquals('50d24733794b928836575c346769be26ee1fb5ffbf73f36933cd22c50116f74e', $queryMap['signature']);
    }

    /**
     * Test case for modifyMultipleOrders.
     *
     * Modify Multiple Orders(TRADE).
     */
    public function testModifyMultipleOrders()
    {
        $modifyMultipleOrdersRequest = new ModifyMultipleOrdersRequest();
        $modifyMultipleOrdersRequest->setBatchOrders(new BatchOrders());

        $response = $this->getApiMock($request)->modifyMultipleOrders($modifyMultipleOrdersRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/batchOrders', $request->getUri()->getPath());
        self::assertEquals('53668e00dc92eb93de0b253c301e9fc0c20042b13db384a0ad94b38688a5a84c', $queryMap['signature']);
    }

    /**
     * Test case for modifyOrder.
     *
     * Modify Order (TRADE).
     */
    public function testModifyOrder()
    {
        $modifyOrderRequest = new ModifyOrderRequest();
        $modifyOrderRequest->setSymbol('');
        $modifyOrderRequest->setSide(Side::BUY);
        $modifyOrderRequest->setQuantity(1.0);
        $modifyOrderRequest->setPrice(1.0);

        $response = $this->getApiMock($request)->modifyOrder($modifyOrderRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/order', $request->getUri()->getPath());
        self::assertEquals('ec03c93d1a8679a9f8ceb481cbeffe902ce084d417a958a874b4db31e0c8c0c8', $queryMap['signature']);
    }

    /**
     * Test case for newAlgoOrder.
     *
     * New Algo Order(TRADE).
     */
    public function testNewAlgoOrder()
    {
        $newAlgoOrderRequest = new NewAlgoOrderRequest();
        $newAlgoOrderRequest->setAlgoType('');
        $newAlgoOrderRequest->setSymbol('');
        $newAlgoOrderRequest->setSide(Side::BUY);
        $newAlgoOrderRequest->setType('');

        $response = $this->getApiMock($request)->newAlgoOrder($newAlgoOrderRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/algoOrder', $request->getUri()->getPath());
        self::assertEquals('2cb0badbb7aa9dcc202c9eb7a490346d9b1444ead428cc697587340c4ffefff0', $queryMap['signature']);
    }

    /**
     * Test case for newOrder.
     *
     * New Order(TRADE).
     */
    public function testNewOrder()
    {
        $newOrderRequest = new NewOrderRequest();
        $newOrderRequest->setSymbol('');
        $newOrderRequest->setSide(Side::BUY);
        $newOrderRequest->setType('');

        $response = $this->getApiMock($request)->newOrder($newOrderRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/order', $request->getUri()->getPath());
        self::assertEquals('2cb0badbb7aa9dcc202c9eb7a490346d9b1444ead428cc697587340c4ffefff0', $queryMap['signature']);
    }

    /**
     * Test case for placeMultipleOrders.
     *
     * Place Multiple Orders(TRADE).
     */
    public function testPlaceMultipleOrders()
    {
        $placeMultipleOrdersRequest = new PlaceMultipleOrdersRequest();
        $placeMultipleOrdersRequest->setBatchOrders(new BatchOrdersPlaceMultipleOrders());

        $response = $this->getApiMock($request)->placeMultipleOrders($placeMultipleOrdersRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/batchOrders', $request->getUri()->getPath());
        self::assertEquals('53668e00dc92eb93de0b253c301e9fc0c20042b13db384a0ad94b38688a5a84c', $queryMap['signature']);
    }

    /**
     * Test case for positionAdlQuantileEstimation.
     *
     * Position ADL Quantile Estimation(USER_DATA).
     */
    public function testPositionAdlQuantileEstimation()
    {
        $symbol = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->positionAdlQuantileEstimation($symbol, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/adlQuantile', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for positionInformationV2.
     *
     * Position Information V2 (USER_DATA).
     */
    public function testPositionInformationV2()
    {
        $symbol = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->positionInformationV2($symbol, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v2/positionRisk', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for positionInformationV3.
     *
     * Position Information V3 (USER_DATA).
     */
    public function testPositionInformationV3()
    {
        $symbol = '';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->positionInformationV3($symbol, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v3/positionRisk', $request->getUri()->getPath());
        self::assertEquals('2cdd1e484bce80021437bee6b762e6a276b1954c3a0c011a16f6f2f6a47aba75', $queryMap['signature']);
    }

    /**
     * Test case for queryAlgoOrder.
     *
     * Query Algo Order (USER_DATA).
     */
    public function testQueryAlgoOrder()
    {
        $algoId = 1;
        $clientAlgoId = '1';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->queryAlgoOrder($algoId, $clientAlgoId, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/algoOrder', $request->getUri()->getPath());
        self::assertEquals('45846156242c5b783dfbafe56f177eb51e9d45a16dcb15e667e825d16d7333a2', $queryMap['signature']);
    }

    /**
     * Test case for queryAllAlgoOrders.
     *
     * Query All Algo Orders (USER_DATA).
     */
    public function testQueryAllAlgoOrders()
    {
        $symbol = '';
        $algoId = 1;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $page = 1;
        $limit = 100;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->queryAllAlgoOrders($symbol, $algoId, $startTime, $endTime, $page, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/allAlgoOrders', $request->getUri()->getPath());
        self::assertEquals('18e6c5ac747aa6e137469fc36cf46ee877229de205dc907b71238333651056ed', $queryMap['signature']);
    }

    /**
     * Test case for queryCurrentOpenOrder.
     *
     * Query Current Open Order (USER_DATA).
     */
    public function testQueryCurrentOpenOrder()
    {
        $symbol = '';
        $orderId = 1;
        $origClientOrderId = '1';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->queryCurrentOpenOrder($symbol, $orderId, $origClientOrderId, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/openOrder', $request->getUri()->getPath());
        self::assertEquals('cbec82483be2ad044b893ffb2e6bc0d55370e378eaea0b4b61d95893bd9cc458', $queryMap['signature']);
    }

    /**
     * Test case for queryOrder.
     *
     * Query Order (USER_DATA).
     */
    public function testQueryOrder()
    {
        $symbol = '';
        $orderId = 1;
        $origClientOrderId = '1';
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->queryOrder($symbol, $orderId, $origClientOrderId, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/order', $request->getUri()->getPath());
        self::assertEquals('cbec82483be2ad044b893ffb2e6bc0d55370e378eaea0b4b61d95893bd9cc458', $queryMap['signature']);
    }

    /**
     * Test case for testOrder.
     *
     * Test Order(TRADE).
     */
    public function testTestOrder()
    {
        $testOrderRequest = new TestOrderRequest();
        $testOrderRequest->setSymbol('');
        $testOrderRequest->setSide(Side::BUY);
        $testOrderRequest->setType('');

        $response = $this->getApiMock($request)->testOrder($testOrderRequest);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/order/test', $request->getUri()->getPath());
        self::assertEquals('2cb0badbb7aa9dcc202c9eb7a490346d9b1444ead428cc697587340c4ffefff0', $queryMap['signature']);
    }

    /**
     * Test case for usersForceOrders.
     *
     * User's Force Orders (USER_DATA).
     */
    public function testUsersForceOrders()
    {
        $symbol = '';
        $autoCloseType = AutoCloseType::LIQUIDATION;
        $startTime = 1623319461670;
        $endTime = 1641782889000;
        $limit = 100;
        $recvWindow = 5000;
        $response = $this->getApiMock($request)->usersForceOrders($symbol, $autoCloseType, $startTime, $endTime, $limit, $recvWindow);

        parse_str($request->getUri(), $queryMap);

        self::assertEquals(200, $response->getStatusCode());
        self::assertEquals('/fapi/v1/forceOrders', $request->getUri()->getPath());
        self::assertEquals('be83f42452513a05ead2e6736601e662fb32a0c0e02e6e8e7e6b2ad91efab5fb', $queryMap['signature']);
    }
}
